
package com.commercetools.api.models.mcp_server;

import java.time.*;
import java.util.*;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.vrap.rmf.base.client.ModelBase;
import io.vrap.rmf.base.client.utils.Generated;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import tools.jackson.databind.annotation.*;

/**
 *  <p>Connection configuration of a Commerce MCP Server. Exposes the <span>Commerce MCP Server tools</span> to AI agents.</p>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
public class CommerceMcpServerConfigImpl implements CommerceMcpServerConfig, ModelBase {

    private String type;

    private String majorVersion;

    private String url;

    private java.util.List<com.commercetools.api.models.mcp_server.McpServerTool> tools;

    private java.util.List<com.commercetools.api.models.mcp_server.ToolCustomization> toolCustomizations;

    private com.commercetools.api.models.mcp_server.McpServerJsonOutputFiltering jsonOutputFiltering;

    private com.commercetools.api.models.mcp_server.McpServerToolOutputFormatting toolOutputFormatting;

    /**
     * create instance with all properties
     */
    @JsonCreator
    CommerceMcpServerConfigImpl(@JsonProperty("majorVersion") final String majorVersion,
            @JsonProperty("url") final String url,
            @JsonProperty("tools") final java.util.List<com.commercetools.api.models.mcp_server.McpServerTool> tools,
            @JsonProperty("toolCustomizations") final java.util.List<com.commercetools.api.models.mcp_server.ToolCustomization> toolCustomizations,
            @JsonProperty("jsonOutputFiltering") final com.commercetools.api.models.mcp_server.McpServerJsonOutputFiltering jsonOutputFiltering,
            @JsonProperty("toolOutputFormatting") final com.commercetools.api.models.mcp_server.McpServerToolOutputFormatting toolOutputFormatting) {
        this.majorVersion = majorVersion;
        this.url = url;
        this.tools = tools;
        this.toolCustomizations = toolCustomizations;
        this.jsonOutputFiltering = jsonOutputFiltering;
        this.toolOutputFormatting = toolOutputFormatting;
        this.type = COMMERCE_MCP;
    }

    /**
     * create empty instance
     */
    public CommerceMcpServerConfigImpl() {
        this.type = COMMERCE_MCP;
    }

    /**
     *  <p>MCP Server type. Determines the shape of the configuration and the set of tools available for this MCP Server.</p>
     */

    public String getType() {
        return this.type;
    }

    /**
     *  <p>Major version of this MCP Server type. Supported versions are <code>v1</code> (deprecated) and <code>v4</code>.</p>
     */

    public String getMajorVersion() {
        return this.majorVersion;
    }

    /**
     *  <p>URL of the MCP Server. Generated by the system from the region, domain, Project key, and MCP Server key. Format: <code>https://mcp.{region}.{domain}/projects/{projectKey}/{mcpServerKey}</code></p>
     */

    public String getUrl() {
        return this.url;
    }

    /**
     *  <p>List of tools enabled for this MCP Server. Use <code>all</code> to enable all available tools, or specify individual tool names such as <code>read_products</code> or <code>create_orders</code>. To reduce the number of LLM turns and improve overall performance, it is advisable to expose only the tools that are necessary, or at least minimize the exposure of tools that are unlikely to be used.</p>
     */

    public java.util.List<com.commercetools.api.models.mcp_server.McpServerTool> getTools() {
        return this.tools;
    }

    /**
     *  <p>Per-tool customizations applied at <code>tools/list</code> and <code>tools/call</code> time, such as overriding a tool's description or constraining its parameters.</p>
     */

    public java.util.List<com.commercetools.api.models.mcp_server.ToolCustomization> getToolCustomizations() {
        return this.toolCustomizations;
    }

    /**
     *  <p>Response field-filtering rules applied to tool responses.</p>
     */

    public com.commercetools.api.models.mcp_server.McpServerJsonOutputFiltering getJsonOutputFiltering() {
        return this.jsonOutputFiltering;
    }

    /**
     *  <p>Output formatting applied to tool responses. When absent, responses are left untouched.</p>
     */

    public com.commercetools.api.models.mcp_server.McpServerToolOutputFormatting getToolOutputFormatting() {
        return this.toolOutputFormatting;
    }

    public void setMajorVersion(final String majorVersion) {
        this.majorVersion = majorVersion;
    }

    public void setUrl(final String url) {
        this.url = url;
    }

    public void setTools(final com.commercetools.api.models.mcp_server.McpServerTool... tools) {
        this.tools = new ArrayList<>(Arrays.asList(tools));
    }

    public void setTools(final java.util.List<com.commercetools.api.models.mcp_server.McpServerTool> tools) {
        this.tools = tools;
    }

    public void setToolCustomizations(
            final com.commercetools.api.models.mcp_server.ToolCustomization... toolCustomizations) {
        this.toolCustomizations = new ArrayList<>(Arrays.asList(toolCustomizations));
    }

    public void setToolCustomizations(
            final java.util.List<com.commercetools.api.models.mcp_server.ToolCustomization> toolCustomizations) {
        this.toolCustomizations = toolCustomizations;
    }

    public void setJsonOutputFiltering(
            final com.commercetools.api.models.mcp_server.McpServerJsonOutputFiltering jsonOutputFiltering) {
        this.jsonOutputFiltering = jsonOutputFiltering;
    }

    public void setToolOutputFormatting(
            final com.commercetools.api.models.mcp_server.McpServerToolOutputFormatting toolOutputFormatting) {
        this.toolOutputFormatting = toolOutputFormatting;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;

        if (o == null || getClass() != o.getClass())
            return false;

        CommerceMcpServerConfigImpl that = (CommerceMcpServerConfigImpl) o;

        return new EqualsBuilder().append(type, that.type)
                .append(majorVersion, that.majorVersion)
                .append(url, that.url)
                .append(tools, that.tools)
                .append(toolCustomizations, that.toolCustomizations)
                .append(jsonOutputFiltering, that.jsonOutputFiltering)
                .append(toolOutputFormatting, that.toolOutputFormatting)
                .append(type, that.type)
                .append(majorVersion, that.majorVersion)
                .append(url, that.url)
                .append(tools, that.tools)
                .append(toolCustomizations, that.toolCustomizations)
                .append(jsonOutputFiltering, that.jsonOutputFiltering)
                .append(toolOutputFormatting, that.toolOutputFormatting)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37).append(type)
                .append(majorVersion)
                .append(url)
                .append(tools)
                .append(toolCustomizations)
                .append(jsonOutputFiltering)
                .append(toolOutputFormatting)
                .toHashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE).append("type", type)
                .append("majorVersion", majorVersion)
                .append("url", url)
                .append("tools", tools)
                .append("toolCustomizations", toolCustomizations)
                .append("jsonOutputFiltering", jsonOutputFiltering)
                .append("toolOutputFormatting", toolOutputFormatting)
                .build();
    }

    @Override
    public CommerceMcpServerConfig copyDeep() {
        return CommerceMcpServerConfig.deepCopy(this);
    }
}
