
package com.commercetools.api.models.mcp_server;

import java.util.*;
import java.util.function.Function;

import javax.annotation.Nullable;

import io.vrap.rmf.base.client.Builder;
import io.vrap.rmf.base.client.utils.Generated;

/**
 * CommerceMcpServerConfigBuilder
 * <hr>
 * Example to create an instance using the builder pattern
 * <div class=code-example>
 * <pre><code class='java'>
 *     CommerceMcpServerConfig commerceMcpServerConfig = CommerceMcpServerConfig.builder()
 *             .majorVersion("{majorVersion}")
 *             .url("{url}")
 *             .plusTools(toolsBuilder -> toolsBuilder)
 *             .plusToolCustomizations(toolCustomizationsBuilder -> toolCustomizationsBuilder)
 *             .build()
 * </code></pre>
 * </div>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
public class CommerceMcpServerConfigBuilder implements Builder<CommerceMcpServerConfig> {

    private String majorVersion;

    private String url;

    private java.util.List<com.commercetools.api.models.mcp_server.McpServerTool> tools;

    private java.util.List<com.commercetools.api.models.mcp_server.ToolCustomization> toolCustomizations;

    @Nullable
    private com.commercetools.api.models.mcp_server.McpServerJsonOutputFiltering jsonOutputFiltering;

    @Nullable
    private com.commercetools.api.models.mcp_server.McpServerToolOutputFormatting toolOutputFormatting;

    /**
     *  <p>Major version of this MCP Server type. Supported versions are <code>v1</code> (deprecated) and <code>v4</code>.</p>
     * @param majorVersion value to be set
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder majorVersion(final String majorVersion) {
        this.majorVersion = majorVersion;
        return this;
    }

    /**
     *  <p>URL of the MCP Server. Generated by the system from the region, domain, Project key, and MCP Server key. Format: <code>https://mcp.{region}.{domain}/projects/{projectKey}/{mcpServerKey}</code></p>
     * @param url value to be set
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder url(final String url) {
        this.url = url;
        return this;
    }

    /**
     *  <p>List of tools enabled for this MCP Server. Use <code>all</code> to enable all available tools, or specify individual tool names such as <code>read_products</code> or <code>create_orders</code>. To reduce the number of LLM turns and improve overall performance, it is advisable to expose only the tools that are necessary, or at least minimize the exposure of tools that are unlikely to be used.</p>
     * @param tools value to be set
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder tools(final com.commercetools.api.models.mcp_server.McpServerTool... tools) {
        this.tools = new ArrayList<>(Arrays.asList(tools));
        return this;
    }

    /**
     *  <p>List of tools enabled for this MCP Server. Use <code>all</code> to enable all available tools, or specify individual tool names such as <code>read_products</code> or <code>create_orders</code>. To reduce the number of LLM turns and improve overall performance, it is advisable to expose only the tools that are necessary, or at least minimize the exposure of tools that are unlikely to be used.</p>
     * @param tools value to be set
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder tools(
            final java.util.List<com.commercetools.api.models.mcp_server.McpServerTool> tools) {
        this.tools = tools;
        return this;
    }

    /**
     *  <p>List of tools enabled for this MCP Server. Use <code>all</code> to enable all available tools, or specify individual tool names such as <code>read_products</code> or <code>create_orders</code>. To reduce the number of LLM turns and improve overall performance, it is advisable to expose only the tools that are necessary, or at least minimize the exposure of tools that are unlikely to be used.</p>
     * @param tools value to be set
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder plusTools(
            final com.commercetools.api.models.mcp_server.McpServerTool... tools) {
        if (this.tools == null) {
            this.tools = new ArrayList<>();
        }
        this.tools.addAll(Arrays.asList(tools));
        return this;
    }

    /**
     *  <p>Per-tool customizations applied at <code>tools/list</code> and <code>tools/call</code> time, such as overriding a tool's description or constraining its parameters.</p>
     * @param toolCustomizations value to be set
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder toolCustomizations(
            final com.commercetools.api.models.mcp_server.ToolCustomization... toolCustomizations) {
        this.toolCustomizations = new ArrayList<>(Arrays.asList(toolCustomizations));
        return this;
    }

    /**
     *  <p>Per-tool customizations applied at <code>tools/list</code> and <code>tools/call</code> time, such as overriding a tool's description or constraining its parameters.</p>
     * @param toolCustomizations value to be set
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder toolCustomizations(
            final java.util.List<com.commercetools.api.models.mcp_server.ToolCustomization> toolCustomizations) {
        this.toolCustomizations = toolCustomizations;
        return this;
    }

    /**
     *  <p>Per-tool customizations applied at <code>tools/list</code> and <code>tools/call</code> time, such as overriding a tool's description or constraining its parameters.</p>
     * @param toolCustomizations value to be set
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder plusToolCustomizations(
            final com.commercetools.api.models.mcp_server.ToolCustomization... toolCustomizations) {
        if (this.toolCustomizations == null) {
            this.toolCustomizations = new ArrayList<>();
        }
        this.toolCustomizations.addAll(Arrays.asList(toolCustomizations));
        return this;
    }

    /**
     *  <p>Per-tool customizations applied at <code>tools/list</code> and <code>tools/call</code> time, such as overriding a tool's description or constraining its parameters.</p>
     * @param builder function to build the toolCustomizations value
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder plusToolCustomizations(
            Function<com.commercetools.api.models.mcp_server.ToolCustomizationBuilder, com.commercetools.api.models.mcp_server.ToolCustomizationBuilder> builder) {
        if (this.toolCustomizations == null) {
            this.toolCustomizations = new ArrayList<>();
        }
        this.toolCustomizations
                .add(builder.apply(com.commercetools.api.models.mcp_server.ToolCustomizationBuilder.of()).build());
        return this;
    }

    /**
     *  <p>Per-tool customizations applied at <code>tools/list</code> and <code>tools/call</code> time, such as overriding a tool's description or constraining its parameters.</p>
     * @param builder function to build the toolCustomizations value
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder withToolCustomizations(
            Function<com.commercetools.api.models.mcp_server.ToolCustomizationBuilder, com.commercetools.api.models.mcp_server.ToolCustomizationBuilder> builder) {
        this.toolCustomizations = new ArrayList<>();
        this.toolCustomizations
                .add(builder.apply(com.commercetools.api.models.mcp_server.ToolCustomizationBuilder.of()).build());
        return this;
    }

    /**
     *  <p>Per-tool customizations applied at <code>tools/list</code> and <code>tools/call</code> time, such as overriding a tool's description or constraining its parameters.</p>
     * @param builder function to build the toolCustomizations value
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder addToolCustomizations(
            Function<com.commercetools.api.models.mcp_server.ToolCustomizationBuilder, com.commercetools.api.models.mcp_server.ToolCustomization> builder) {
        return plusToolCustomizations(
            builder.apply(com.commercetools.api.models.mcp_server.ToolCustomizationBuilder.of()));
    }

    /**
     *  <p>Per-tool customizations applied at <code>tools/list</code> and <code>tools/call</code> time, such as overriding a tool's description or constraining its parameters.</p>
     * @param builder function to build the toolCustomizations value
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder setToolCustomizations(
            Function<com.commercetools.api.models.mcp_server.ToolCustomizationBuilder, com.commercetools.api.models.mcp_server.ToolCustomization> builder) {
        return toolCustomizations(builder.apply(com.commercetools.api.models.mcp_server.ToolCustomizationBuilder.of()));
    }

    /**
     *  <p>Response field-filtering rules applied to tool responses.</p>
     * @param builder function to build the jsonOutputFiltering value
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder jsonOutputFiltering(
            Function<com.commercetools.api.models.mcp_server.McpServerJsonOutputFilteringBuilder, com.commercetools.api.models.mcp_server.McpServerJsonOutputFilteringBuilder> builder) {
        this.jsonOutputFiltering = builder
                .apply(com.commercetools.api.models.mcp_server.McpServerJsonOutputFilteringBuilder.of())
                .build();
        return this;
    }

    /**
     *  <p>Response field-filtering rules applied to tool responses.</p>
     * @param builder function to build the jsonOutputFiltering value
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder withJsonOutputFiltering(
            Function<com.commercetools.api.models.mcp_server.McpServerJsonOutputFilteringBuilder, com.commercetools.api.models.mcp_server.McpServerJsonOutputFiltering> builder) {
        this.jsonOutputFiltering = builder
                .apply(com.commercetools.api.models.mcp_server.McpServerJsonOutputFilteringBuilder.of());
        return this;
    }

    /**
     *  <p>Response field-filtering rules applied to tool responses.</p>
     * @param jsonOutputFiltering value to be set
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder jsonOutputFiltering(
            @Nullable final com.commercetools.api.models.mcp_server.McpServerJsonOutputFiltering jsonOutputFiltering) {
        this.jsonOutputFiltering = jsonOutputFiltering;
        return this;
    }

    /**
     *  <p>Output formatting applied to tool responses. When absent, responses are left untouched.</p>
     * @param toolOutputFormatting value to be set
     * @return Builder
     */

    public CommerceMcpServerConfigBuilder toolOutputFormatting(
            @Nullable final com.commercetools.api.models.mcp_server.McpServerToolOutputFormatting toolOutputFormatting) {
        this.toolOutputFormatting = toolOutputFormatting;
        return this;
    }

    /**
     *  <p>Major version of this MCP Server type. Supported versions are <code>v1</code> (deprecated) and <code>v4</code>.</p>
     * @return majorVersion
     */

    public String getMajorVersion() {
        return this.majorVersion;
    }

    /**
     *  <p>URL of the MCP Server. Generated by the system from the region, domain, Project key, and MCP Server key. Format: <code>https://mcp.{region}.{domain}/projects/{projectKey}/{mcpServerKey}</code></p>
     * @return url
     */

    public String getUrl() {
        return this.url;
    }

    /**
     *  <p>List of tools enabled for this MCP Server. Use <code>all</code> to enable all available tools, or specify individual tool names such as <code>read_products</code> or <code>create_orders</code>. To reduce the number of LLM turns and improve overall performance, it is advisable to expose only the tools that are necessary, or at least minimize the exposure of tools that are unlikely to be used.</p>
     * @return tools
     */

    public java.util.List<com.commercetools.api.models.mcp_server.McpServerTool> getTools() {
        return this.tools;
    }

    /**
     *  <p>Per-tool customizations applied at <code>tools/list</code> and <code>tools/call</code> time, such as overriding a tool's description or constraining its parameters.</p>
     * @return toolCustomizations
     */

    public java.util.List<com.commercetools.api.models.mcp_server.ToolCustomization> getToolCustomizations() {
        return this.toolCustomizations;
    }

    /**
     *  <p>Response field-filtering rules applied to tool responses.</p>
     * @return jsonOutputFiltering
     */

    @Nullable
    public com.commercetools.api.models.mcp_server.McpServerJsonOutputFiltering getJsonOutputFiltering() {
        return this.jsonOutputFiltering;
    }

    /**
     *  <p>Output formatting applied to tool responses. When absent, responses are left untouched.</p>
     * @return toolOutputFormatting
     */

    @Nullable
    public com.commercetools.api.models.mcp_server.McpServerToolOutputFormatting getToolOutputFormatting() {
        return this.toolOutputFormatting;
    }

    /**
     * builds CommerceMcpServerConfig with checking for non-null required values
     * @return CommerceMcpServerConfig
     */
    public CommerceMcpServerConfig build() {
        Objects.requireNonNull(majorVersion, CommerceMcpServerConfig.class + ": majorVersion is missing");
        Objects.requireNonNull(url, CommerceMcpServerConfig.class + ": url is missing");
        Objects.requireNonNull(tools, CommerceMcpServerConfig.class + ": tools is missing");
        Objects.requireNonNull(toolCustomizations, CommerceMcpServerConfig.class + ": toolCustomizations is missing");
        return new CommerceMcpServerConfigImpl(majorVersion, url, tools, toolCustomizations, jsonOutputFiltering,
            toolOutputFormatting);
    }

    /**
     * builds CommerceMcpServerConfig without checking for non-null required values
     * @return CommerceMcpServerConfig
     */
    public CommerceMcpServerConfig buildUnchecked() {
        return new CommerceMcpServerConfigImpl(majorVersion, url, tools, toolCustomizations, jsonOutputFiltering,
            toolOutputFormatting);
    }

    /**
     * factory method for an instance of CommerceMcpServerConfigBuilder
     * @return builder
     */
    public static CommerceMcpServerConfigBuilder of() {
        return new CommerceMcpServerConfigBuilder();
    }

    /**
     * create builder for CommerceMcpServerConfig instance
     * @param template instance with prefilled values for the builder
     * @return builder
     */
    public static CommerceMcpServerConfigBuilder of(final CommerceMcpServerConfig template) {
        CommerceMcpServerConfigBuilder builder = new CommerceMcpServerConfigBuilder();
        builder.majorVersion = template.getMajorVersion();
        builder.url = template.getUrl();
        builder.tools = template.getTools();
        builder.toolCustomizations = template.getToolCustomizations();
        builder.jsonOutputFiltering = template.getJsonOutputFiltering();
        builder.toolOutputFormatting = template.getToolOutputFormatting();
        return builder;
    }

}
