
package com.commercetools.api.models.mcp_server;

import java.time.*;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.*;

import io.vrap.rmf.base.client.utils.Generated;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import tools.jackson.databind.annotation.*;

/**
 *  <p>Connection configuration of a Commerce MCP Server. Exposes the <span>Commerce MCP Server tools</span> to AI agents.</p>
 *
 * <hr>
 * Example to create an instance using the builder pattern
 * <div class=code-example>
 * <pre><code class='java'>
 *     CommerceMcpServerConfig commerceMcpServerConfig = CommerceMcpServerConfig.builder()
 *             .majorVersion("{majorVersion}")
 *             .url("{url}")
 *             .plusTools(toolsBuilder -> toolsBuilder)
 *             .plusToolCustomizations(toolCustomizationsBuilder -> toolCustomizationsBuilder)
 *             .build()
 * </code></pre>
 * </div>
 */
@io.vrap.rmf.base.client.utils.json.SubType("CommerceMCP")
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
@JsonDeserialize(as = CommerceMcpServerConfigImpl.class)
public interface CommerceMcpServerConfig extends McpServerConfig {

    /**
     * discriminator value for CommerceMcpServerConfig
     */
    String COMMERCE_MCP = "CommerceMCP";

    /**
     *  <p>Major version of this MCP Server type. Supported versions are <code>v1</code> (deprecated) and <code>v4</code>.</p>
     * @return majorVersion
     */
    @NotNull
    @JsonProperty("majorVersion")
    public String getMajorVersion();

    /**
     *  <p>URL of the MCP Server. Generated by the system from the region, domain, Project key, and MCP Server key. Format: <code>https://mcp.{region}.{domain}/projects/{projectKey}/{mcpServerKey}</code></p>
     * @return url
     */
    @NotNull
    @JsonProperty("url")
    public String getUrl();

    /**
     *  <p>List of tools enabled for this MCP Server. Use <code>all</code> to enable all available tools, or specify individual tool names such as <code>read_products</code> or <code>create_orders</code>. To reduce the number of LLM turns and improve overall performance, it is advisable to expose only the tools that are necessary, or at least minimize the exposure of tools that are unlikely to be used.</p>
     * @return tools
     */
    @NotNull
    @JsonProperty("tools")
    public List<McpServerTool> getTools();

    /**
     *  <p>Per-tool customizations applied at <code>tools/list</code> and <code>tools/call</code> time, such as overriding a tool's description or constraining its parameters.</p>
     * @return toolCustomizations
     */
    @NotNull
    @Valid
    @JsonProperty("toolCustomizations")
    public List<ToolCustomization> getToolCustomizations();

    /**
     *  <p>Response field-filtering rules applied to tool responses.</p>
     * @return jsonOutputFiltering
     */
    @Valid
    @JsonProperty("jsonOutputFiltering")
    public McpServerJsonOutputFiltering getJsonOutputFiltering();

    /**
     *  <p>Output formatting applied to tool responses. When absent, responses are left untouched.</p>
     * @return toolOutputFormatting
     */

    @JsonProperty("toolOutputFormatting")
    public McpServerToolOutputFormatting getToolOutputFormatting();

    /**
     *  <p>Major version of this MCP Server type. Supported versions are <code>v1</code> (deprecated) and <code>v4</code>.</p>
     * @param majorVersion value to be set
     */

    public void setMajorVersion(final String majorVersion);

    /**
     *  <p>URL of the MCP Server. Generated by the system from the region, domain, Project key, and MCP Server key. Format: <code>https://mcp.{region}.{domain}/projects/{projectKey}/{mcpServerKey}</code></p>
     * @param url value to be set
     */

    public void setUrl(final String url);

    /**
     *  <p>List of tools enabled for this MCP Server. Use <code>all</code> to enable all available tools, or specify individual tool names such as <code>read_products</code> or <code>create_orders</code>. To reduce the number of LLM turns and improve overall performance, it is advisable to expose only the tools that are necessary, or at least minimize the exposure of tools that are unlikely to be used.</p>
     * @param tools values to be set
     */

    @JsonIgnore
    public void setTools(final McpServerTool... tools);

    /**
     *  <p>List of tools enabled for this MCP Server. Use <code>all</code> to enable all available tools, or specify individual tool names such as <code>read_products</code> or <code>create_orders</code>. To reduce the number of LLM turns and improve overall performance, it is advisable to expose only the tools that are necessary, or at least minimize the exposure of tools that are unlikely to be used.</p>
     * @param tools values to be set
     */

    public void setTools(final List<McpServerTool> tools);

    /**
     *  <p>Per-tool customizations applied at <code>tools/list</code> and <code>tools/call</code> time, such as overriding a tool's description or constraining its parameters.</p>
     * @param toolCustomizations values to be set
     */

    @JsonIgnore
    public void setToolCustomizations(final ToolCustomization... toolCustomizations);

    /**
     *  <p>Per-tool customizations applied at <code>tools/list</code> and <code>tools/call</code> time, such as overriding a tool's description or constraining its parameters.</p>
     * @param toolCustomizations values to be set
     */

    public void setToolCustomizations(final List<ToolCustomization> toolCustomizations);

    /**
     *  <p>Response field-filtering rules applied to tool responses.</p>
     * @param jsonOutputFiltering value to be set
     */

    public void setJsonOutputFiltering(final McpServerJsonOutputFiltering jsonOutputFiltering);

    /**
     *  <p>Output formatting applied to tool responses. When absent, responses are left untouched.</p>
     * @param toolOutputFormatting value to be set
     */

    public void setToolOutputFormatting(final McpServerToolOutputFormatting toolOutputFormatting);

    /**
     * factory method
     * @return instance of CommerceMcpServerConfig
     */
    public static CommerceMcpServerConfig of() {
        return new CommerceMcpServerConfigImpl();
    }

    /**
     * factory method to create a shallow copy CommerceMcpServerConfig
     * @param template instance to be copied
     * @return copy instance
     */
    public static CommerceMcpServerConfig of(final CommerceMcpServerConfig template) {
        CommerceMcpServerConfigImpl instance = new CommerceMcpServerConfigImpl();
        instance.setMajorVersion(template.getMajorVersion());
        instance.setUrl(template.getUrl());
        instance.setTools(template.getTools());
        instance.setToolCustomizations(template.getToolCustomizations());
        instance.setJsonOutputFiltering(template.getJsonOutputFiltering());
        instance.setToolOutputFormatting(template.getToolOutputFormatting());
        return instance;
    }

    public CommerceMcpServerConfig copyDeep();

    /**
     * factory method to create a deep copy of CommerceMcpServerConfig
     * @param template instance to be copied
     * @return copy instance
     */
    @Nullable
    public static CommerceMcpServerConfig deepCopy(@Nullable final CommerceMcpServerConfig template) {
        if (template == null) {
            return null;
        }
        CommerceMcpServerConfigImpl instance = new CommerceMcpServerConfigImpl();
        instance.setMajorVersion(template.getMajorVersion());
        instance.setUrl(template.getUrl());
        instance.setTools(Optional.ofNullable(template.getTools()).map(ArrayList::new).orElse(null));
        instance.setToolCustomizations(Optional.ofNullable(template.getToolCustomizations())
                .map(t -> t.stream()
                        .map(com.commercetools.api.models.mcp_server.ToolCustomization::deepCopy)
                        .collect(Collectors.toList()))
                .orElse(null));
        instance.setJsonOutputFiltering(com.commercetools.api.models.mcp_server.McpServerJsonOutputFiltering
                .deepCopy(template.getJsonOutputFiltering()));
        instance.setToolOutputFormatting(template.getToolOutputFormatting());
        return instance;
    }

    /**
     * builder factory method for CommerceMcpServerConfig
     * @return builder
     */
    public static CommerceMcpServerConfigBuilder builder() {
        return CommerceMcpServerConfigBuilder.of();
    }

    /**
     * create builder for CommerceMcpServerConfig instance
     * @param template instance with prefilled values for the builder
     * @return builder
     */
    public static CommerceMcpServerConfigBuilder builder(final CommerceMcpServerConfig template) {
        return CommerceMcpServerConfigBuilder.of(template);
    }

    /**
     * accessor map function
     * @param <T> mapped type
     * @param helper function to map the object
     * @return mapped value
     */
    default <T> T withCommerceMcpServerConfig(Function<CommerceMcpServerConfig, T> helper) {
        return helper.apply(this);
    }

    /**
     * gives a TypeReference for usage with Jackson DataBind
     * @return TypeReference
     */
    public static tools.jackson.core.type.TypeReference<CommerceMcpServerConfig> typeReference() {
        return new tools.jackson.core.type.TypeReference<CommerceMcpServerConfig>() {
            @Override
            public String toString() {
                return "TypeReference<CommerceMcpServerConfig>";
            }
        };
    }
}
