#%RAML 1.0 Extension
usage: Adds JavaSDK extended functionality
extends: api.raml
annotationTypes:
  java-mixin:
    type: string
    allowedTargets: TypeDeclaration

types:
  BaseAddress:
    (java-extends): 'com.commercetools.api.models.WithKey, BaseAddressMixin'
  Address:
    (java-extends): 'com.commercetools.api.models.Customizable<Address>'
    properties:
      id:
        required: false
  AddressDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<AddressDraft>'
  Asset:
    (java-extends): 'com.commercetools.api.models.Customizable<Asset>, com.commercetools.api.models.WithKey'
  AssetSource:
    (java-extends): 'com.commercetools.api.models.WithKey'
  AssetDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<AssetDraft>, com.commercetools.api.models.WithKey'
  AssetDimensions:
    (java-extends): 'com.commercetools.api.models.Customizable<AssetDimensions>'
    (java-mixin): |
      default Integer getWidth() {
          return getW();
      }

      default Integer getHeight() {
          return getH();
      }
  LocalizedString:
    (java-extends): 'com.commercetools.api.models.common.LocalizedStringUtil'
  ReplicaCartDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
    (java-mixin): |
      @JsonIgnore
      @Deprecated
      public default void setReference(final Object reference) {
          setReference((Reference)reference);
      };
    properties:
      reference:
        type: Reference
  CustomShippingDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  ShippingDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  Cart:
    (java-extends): 'CartMixin, com.commercetools.api.models.DomainResource<Cart>, com.commercetools.api.models.Referencable<Cart>, com.commercetools.api.models.ResourceIdentifiable<Cart>, com.commercetools.api.models.Customizable<Cart>, com.commercetools.api.models.order.OrderLike<Cart>, com.commercetools.api.models.WithKey'
  CartDiscount:
    (java-extends): 'CartDiscountMixin, com.commercetools.api.models.DomainResource<CartDiscount>, com.commercetools.api.models.Referencable<CartDiscount>, com.commercetools.api.models.ResourceIdentifiable<CartDiscount>, com.commercetools.api.models.Customizable<CartDiscount>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.CART_DISCOUNT;
      }
  Category:
    (java-extends): 'CategoryMixin, com.commercetools.api.models.DomainResource<Category>, com.commercetools.api.models.Referencable<Category>, com.commercetools.api.models.ResourceIdentifiable<Category>, com.commercetools.api.models.Customizable<Category>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.CATEGORY;
      }
  Channel:
    (java-extends): 'ChannelMixin, com.commercetools.api.models.DomainResource<Channel>, com.commercetools.api.models.Referencable<Channel>, com.commercetools.api.models.ResourceIdentifiable<Channel>, com.commercetools.api.models.Customizable<Channel>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.CHANNEL;
      }
  CustomObject:
    (java-extends): 'CustomObjectMixin, com.commercetools.api.models.DomainResource<CustomObject>, com.commercetools.api.models.Referencable<CustomObject>'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.KEY_VALUE_DOCUMENT;
      }
  CustomObjectPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<CustomObject>'
  CustomObjectReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<CustomObject>'
  Customer:
    (java-extends): 'CustomerMixin, com.commercetools.api.models.DomainResource<Customer>, com.commercetools.api.models.Referencable<Customer>, com.commercetools.api.models.ResourceIdentifiable<Customer>, com.commercetools.api.models.Customizable<Customer>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.CUSTOMER;
      }
  CustomerDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<CustomerDraft>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static CustomerDraftBuilder builder(Customer customer) {
          return CustomerDraftMixin.builder(customer);
      }
  CustomerPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Customer>'
  CustomerReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<Customer>'
  CustomerResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<Customer>'
  CustomerUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<CustomerUpdate,
      CustomerUpdateAction, CustomerUpdateBuilder>'
  CustomerUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<CustomerUpdateAction>'
  CustomerGroup:
    (java-extends): 'CustomerGroupMixin, com.commercetools.api.models.DomainResource<CustomerGroup>, com.commercetools.api.models.Referencable<CustomerGroup>, com.commercetools.api.models.ResourceIdentifiable<CustomerGroup>, com.commercetools.api.models.Customizable<CustomerGroup>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.CUSTOMER_GROUP;
      }
  CustomerGroupDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<CustomerGroupDraft>, com.commercetools.api.models.WithKey'
  CustomerGroupPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<CustomerGroup>'
  CustomerGroupReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<CustomerGroup>'
  CustomerGroupResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<CustomerGroup>'
  CustomerGroupUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<CustomerGroupUpdate,
      CustomerGroupUpdateAction, CustomerGroupUpdateBuilder>'
  CustomerGroupUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<CustomerGroupUpdateAction>'
  DiscountCode:
    (java-extends): 'DiscountCodeMixin, com.commercetools.api.models.DomainResource<DiscountCode>, com.commercetools.api.models.Referencable<DiscountCode>, com.commercetools.api.models.ResourceIdentifiable<DiscountCode>, com.commercetools.api.models.Customizable<DiscountCode>'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.DISCOUNT_CODE;
      }
  DiscountCodeDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<DiscountCodeDraft>'
  DiscountCodePagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<DiscountCode>'
  DiscountCodeReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<DiscountCode>'
  DiscountCodeResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<DiscountCode>'
  DiscountCodeUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<DiscountCodeUpdate,
      DiscountCodeUpdateAction, DiscountCodeUpdateBuilder>'
  DiscountCodeUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<DiscountCodeUpdateAction>'
  Extension:
    (java-extends): 'com.commercetools.api.models.DomainResource<Extension>, com.commercetools.api.models.WithKey'
  ExtensionDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  ExtensionPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Extension>'
  ExtensionUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<ExtensionUpdate,
      ExtensionUpdateAction, ExtensionUpdateBuilder>'
  ExtensionUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<ExtensionUpdateAction>'
  InventoryEntry:
    (java-extends): 'InventoryEntryMixin, com.commercetools.api.models.DomainResource<InventoryEntry>, com.commercetools.api.models.Referencable<InventoryEntry>, com.commercetools.api.models.ResourceIdentifiable<InventoryEntry>, com.commercetools.api.models.Customizable<InventoryEntry>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.INVENTORY_ENTRY;
      }
  InventoryEntryDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<InventoryEntryDraft>, com.commercetools.api.models.WithKey'
  InventoryPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<InventoryEntry>'
  InventoryEntryReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<InventoryEntry>'
  InventoryEntryResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<InventoryEntry>'
  InventoryEntryUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<InventoryEntryUpdate,
      InventoryEntryUpdateAction, InventoryEntryUpdateBuilder>'
  InventoryEntryUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<InventoryEntryUpdateAction>'
  Order:
    (java-extends): 'OrderMixin, com.commercetools.api.models.DomainResource<Order>, com.commercetools.api.models.Referencable<Order>, com.commercetools.api.models.ResourceIdentifiable<Order>, com.commercetools.api.models.Customizable<Order>, com.commercetools.api.models.order.OrderLike<Order>'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.ORDER;
      }
  OrderImportDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<OrderImportDraft>'
  OrderPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Order>'
  OrderReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<Order>'
  OrderResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<Order>'
  OrderUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<OrderUpdate, OrderUpdateAction, OrderUpdateBuilder>'
  OrderUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<OrderUpdateAction>'

  OrderEdit:
    (java-extends): 'OrderEditMixin, com.commercetools.api.models.DomainResource<OrderEdit>, com.commercetools.api.models.Referencable<OrderEdit>, com.commercetools.api.models.ResourceIdentifiable<OrderEdit>, com.commercetools.api.models.Customizable<OrderEdit>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.ORDER_EDIT;
      }
  OrderEditPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<OrderEdit>'
  OrderEditReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<OrderEdit>'
  OrderEditResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<OrderEdit>'
  OrderEditUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<OrderEditUpdate, OrderEditUpdateAction, OrderEditUpdateBuilder>'
  OrderEditUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<OrderEditUpdateAction>'
  StagedOrderUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<StagedOrderUpdateAction>'
  StagedOrderAddCustomLineItemAction:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<StagedOrderAddCustomLineItemAction>'
  StagedOrderAddDeliveryAction:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<StagedOrderAddDeliveryAction>'
  StagedOrderAddLineItemAction:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<StagedOrderAddLineItemAction>'
  OrderAddDeliveryAction:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<OrderAddDeliveryAction>'

  Payment:
    (java-extends): 'PaymentMixin, com.commercetools.api.models.DomainResource<Payment>, com.commercetools.api.models.Referencable<Payment>, com.commercetools.api.models.ResourceIdentifiable<Payment>, com.commercetools.api.models.Customizable<Payment>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.PAYMENT;
      }
  PaymentDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<PaymentDraft>, com.commercetools.api.models.WithKey'
  PaymentPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Payment>'
  PaymentReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<Payment>'
  PaymentResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<Payment>'
  PaymentUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<PaymentUpdate,
      PaymentUpdateAction, PaymentUpdateBuilder>'
  PaymentUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<PaymentUpdateAction>'
  Transaction:
    (java-extends): 'com.commercetools.api.models.Customizable<Transaction>'
  TransactionDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<TransactionDraft>'
  Product:
    (java-extends): 'ProductMixin, com.commercetools.api.models.DomainResource<Product>, com.commercetools.api.models.Referencable<Product>, com.commercetools.api.models.ResourceIdentifiable<Product>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.PRODUCT;
      }
  ProductDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  ProductData:
    (java-extends): 'ProductDataLike'
  ProductPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Product>'
  ProductProjection:
    (java-extends): 'ProductDataLike, com.commercetools.api.models.DomainResource<ProductProjection>, com.commercetools.api.models.WithKey'
  ProductVariant:
    (java-extends): 'com.commercetools.api.models.WithKey'
  ProductVariantDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  ProductProjectionPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<ProductProjection>'
  ProductProjectionPagedSearchResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<ProductProjection>'
  ProductReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<Product>'
  ProductResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<Product>'
  ProductUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<ProductUpdate,
      ProductUpdateAction, ProductUpdateBuilder>'
  ProductUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<ProductUpdateAction>'
  ProductDiscount:
    (java-extends): 'ProductDiscountMixin, com.commercetools.api.models.DomainResource<ProductDiscount>, com.commercetools.api.models.Referencable<ProductDiscount>, com.commercetools.api.models.ResourceIdentifiable<ProductDiscount>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.PRODUCT_DISCOUNT;
      }
  ProductDiscountDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  ProductDiscountPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<ProductDiscount>'
  ProductDiscountReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<ProductDiscount>'
  ProductDiscountResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<ProductDiscount>'
  ProductDiscountUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<ProductDiscountUpdate,
      ProductDiscountUpdateAction, ProductDiscountUpdateBuilder>'
  ProductDiscountUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<ProductDiscountUpdateAction>'
  ProductType:
    (java-extends): 'AttributeDefinitionContainer, ProductTypeMixin, com.commercetools.api.models.DomainResource<ProductType>, com.commercetools.api.models.Referencable<ProductType>, com.commercetools.api.models.ResourceIdentifiable<ProductType>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.PRODUCT_TYPE;
      }

      default com.commercetools.api.models.product_type.AttributeDefinition getAttribute(final String attributeName) {
          return AttributeDefinitionContainer.super.getAttribute(attributeName);
      }

      @Override
      default Optional<AttributeDefinition> findAttribute(final String attributeName) {
          return AttributeDefinitionContainer.super.findAttribute(attributeName);
      }
  ProductTypeDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  ProductTypePagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<ProductType>'
  ProductTypeReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<ProductType>'
  ProductTypeResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<ProductType>'
  ProductTypeUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<ProductTypeUpdate,
      ProductTypeUpdateAction, ProductTypeUpdateBuilder>'
  ProductTypeUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<ProductTypeUpdateAction>'
  Project:
    (java-extends): 'com.commercetools.api.models.WithKey'
  ProjectUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<ProjectUpdate,
      ProjectUpdateAction, ProjectUpdateBuilder>'
  ProjectUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<ProjectUpdateAction>'

  AssignedProductSelectionPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<AssignedProductSelection>'

  ProductSelection:
    (java-extends): 'ProductSelectionMixin, com.commercetools.api.models.DomainResource<ProductSelection>, com.commercetools.api.models.Referencable<ProductSelection>, com.commercetools.api.models.ResourceIdentifiable<ProductSelection>, com.commercetools.api.models.Customizable<ProductSelection>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.PRODUCT_SELECTION;
      }
  ProductSelectionDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<ProductSelectionDraft>, com.commercetools.api.models.WithKey'
  ProductSelectionPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<ProductSelection>'
  ProductSelectionProductPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<AssignedProductReference>'
  ProductSelectionReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<ProductSelection>'
  ProductSelectionResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<ProductSelection>'
  ProductSelectionUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<ProductSelectionUpdate,
      ProductSelectionUpdateAction, ProductSelectionUpdateBuilder>'
  ProductSelectionUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<ProductSelectionUpdateAction>'
  ProductsInStorePagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<ProductSelectionAssignment>'

  Quote:
    (java-extends): 'QuoteMixin, com.commercetools.api.models.DomainResource<Quote>, com.commercetools.api.models.Referencable<Quote>, com.commercetools.api.models.ResourceIdentifiable<Quote>, com.commercetools.api.models.Customizable<Quote>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.QUOTE;
      }
  QuoteDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<QuoteDraft>, com.commercetools.api.models.WithKey'
  QuotePagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Quote>'
  QuoteReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<Quote>'
  QuoteResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<Quote>'
  QuoteUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<QuoteUpdate,
      QuoteUpdateAction, QuoteUpdateBuilder>'
  QuoteUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<QuoteUpdateAction>'
  QuoteRequestPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<QuoteRequest>'
  QuoteRequestReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<QuoteRequest>'
  QuoteRequestResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<QuoteRequest>'
  QuoteRequestUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<QuoteRequestUpdate,
      QuoteRequestUpdateAction, QuoteRequestUpdateBuilder>'
  QuoteRequestUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<QuoteRequestUpdateAction>'
  QuoteRequest:
    (java-extends): 'com.commercetools.api.models.WithKey'
  QuoteRequestDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  StagedQuote:
    (java-extends): 'com.commercetools.api.models.WithKey'
  StagedQuoteDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'

  Review:
    (java-extends): 'ReviewMixin, com.commercetools.api.models.DomainResource<Review>, com.commercetools.api.models.Referencable<Review>, com.commercetools.api.models.ResourceIdentifiable<Review>, com.commercetools.api.models.Customizable<Review>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.REVIEW;
      }

      @Deprecated
      @JsonIgnore
      public default void setTarget(final Object target) {
          setTarget((Reference)target);
      };
    properties:
      target?:
        type: Reference
  ReviewDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<ReviewDraft>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      @Deprecated
      @JsonIgnore
      public default void setTarget(final Object target) {
          setTarget((ResourceIdentifier)target);
      };
    properties:
      target?:
        type: ResourceIdentifier
  ReviewPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Review>'
  ReviewReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<Review>'
  ReviewResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<Review>'
  ReviewUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<ReviewUpdate,
      ReviewUpdateAction, ReviewUpdateBuilder>'
  ReviewUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<ReviewUpdateAction>'

  ShippingMethod:
    (java-extends): 'ShippingMethodMixin, com.commercetools.api.models.DomainResource<ShippingMethod>, com.commercetools.api.models.Referencable<ShippingMethod>, com.commercetools.api.models.ResourceIdentifiable<ShippingMethod>, com.commercetools.api.models.Customizable<ShippingMethod>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.SHIPPING_METHOD;
      }
  ShippingMethodDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<ShippingMethodDraft>, com.commercetools.api.models.WithKey'
  ShippingMethodPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<ShippingMethod>'
  ShippingMethodReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<ShippingMethod>'
  ShippingMethodResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<ShippingMethod>'
  ShippingMethodUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<ShippingMethodUpdate,
      ShippingMethodUpdateAction, ShippingMethodUpdateBuilder>'
  ShippingMethodUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<ShippingMethodUpdateAction>'

  ShoppingList:
    (java-extends): 'ShoppingListMixin, com.commercetools.api.models.DomainResource<ShoppingList>, com.commercetools.api.models.Referencable<ShoppingList>, com.commercetools.api.models.ResourceIdentifiable<ShoppingList>, com.commercetools.api.models.Customizable<ShoppingList>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.SHOPPING_LIST;
      }
  ShoppingListDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<ShoppingListDraft>, com.commercetools.api.models.WithKey'
  ShoppingListPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<ShoppingList>'
  ShoppingListReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<ShoppingList>'
  ShoppingListResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<ShoppingList>'
  ShoppingListUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<ShoppingListUpdate,
      ShoppingListUpdateAction, ShoppingListUpdateBuilder>'
  ShoppingListUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<ShoppingListUpdateAction>'
  ShoppingListLineItem:
    (java-extends): 'com.commercetools.api.models.Customizable<ShoppingListLineItem>'
  ShoppingListLineItemDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<ShoppingListLineItemDraft>'
  ShoppingListAddLineItemAction:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<ShoppingListAddLineItemAction>'
  ShoppingListAddTextLineItemAction:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<ShoppingListAddTextLineItemAction>'
  TextLineItem:
    (java-extends): 'com.commercetools.api.models.Customizable<TextLineItem>'
  TextLineItemDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<TextLineItemDraft>'

  StagedQuotePagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<StagedQuote>'
  StagedQuoteReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<StagedQuote>'
  StagedQuoteResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<StagedQuote>'
  StagedQuoteUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<StagedQuoteUpdate,
      StagedQuoteUpdateAction, StagedQuoteUpdateBuilder>'
  StagedQuoteUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<StagedQuoteUpdateAction>'

  StandalonePrice:
    (java-extends): 'StandalonePriceMixin, com.commercetools.api.models.DomainResource<StandalonePrice>, com.commercetools.api.models.Referencable<StandalonePrice>, com.commercetools.api.models.ResourceIdentifiable<StandalonePrice>, com.commercetools.api.models.Customizable<StandalonePrice>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.STANDALONE_PRICE;
      }
  StandalonePriceDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<StandalonePriceDraft>, com.commercetools.api.models.WithKey'
  StandalonePricePagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<StandalonePrice>'
  StandalonePriceUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<StandalonePriceUpdate,
      StandalonePriceUpdateAction, StandalonePriceUpdateBuilder>'
  StandalonePriceUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<StandalonePriceUpdateAction>'

  State:
    (java-extends): 'StateMixin, com.commercetools.api.models.DomainResource<State>, com.commercetools.api.models.Referencable<State>, com.commercetools.api.models.ResourceIdentifiable<State>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.STATE;
      }
  StateDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  StatePagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<State>'
  StateReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<State>'
  StateResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<State>'
  StateUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<StateUpdate,
      StateUpdateAction, StateUpdateBuilder>'
  StateUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<StateUpdateAction>'

  Store:
    (java-extends): 'StoreMixin, com.commercetools.api.models.DomainResource<Store>, com.commercetools.api.models.Referencable<Store>, com.commercetools.api.models.ResourceIdentifiable<Store>, com.commercetools.api.models.Customizable<Store>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.STORE;
      }
  StoreDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<StoreDraft>, com.commercetools.api.models.WithKey'
  StorePagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Store>'
  StoreReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<Store>'
  StoreResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<Store>'
  StoreUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<StoreUpdate,
      StoreUpdateAction, StoreUpdateBuilder>'
  StoreUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<StoreUpdateAction>'

  Subscription:
    (java-extends): 'com.commercetools.api.models.DomainResource<Subscription>, com.commercetools.api.models.WithKey'
  SubscriptionDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  SubscriptionPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Subscription>'
  SubscriptionUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<SubscriptionUpdate,
      SubscriptionUpdateAction, SubscriptionUpdateBuilder>'
  SubscriptionUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<SubscriptionUpdateAction>'

  TaxCategory:
    (java-extends): 'TaxCategoryMixin, com.commercetools.api.models.DomainResource<TaxCategory>, com.commercetools.api.models.Referencable<TaxCategory>, com.commercetools.api.models.ResourceIdentifiable<TaxCategory>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.TAX_CATEGORY;
      }
  TaxCategoryDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  TaxCategoryPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<TaxCategory>'
  TaxCategoryReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<TaxCategory>'
  TaxCategoryResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<TaxCategory>'
  TaxCategoryUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<TaxCategoryUpdate,
      TaxCategoryUpdateAction, TaxCategoryUpdateBuilder>'
  TaxCategoryUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<TaxCategoryUpdateAction>'

  Type:
    (java-extends): 'TypeMixin, com.commercetools.api.models.DomainResource<Type>, com.commercetools.api.models.Referencable<Type>, com.commercetools.api.models.ResourceIdentifiable<Type>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.TYPE;
      }

      @Nullable
      default FieldDefinition getFieldDefinitionByName(final String name) {
          return getFieldDefinitions().stream().filter(def -> def.getName().equals(name)).findFirst().orElse(null);
      }
  TypeDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  TypePagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Type>'
  TypeResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<Type>'
  TypeUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<TypeUpdate,
      TypeUpdateAction, TypeUpdateBuilder>'
  TypeUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<TypeUpdateAction>'

  Zone:
    (java-extends): 'ZoneMixin, com.commercetools.api.models.DomainResource<Zone>, com.commercetools.api.models.Referencable<Zone>, com.commercetools.api.models.ResourceIdentifiable<Zone>, com.commercetools.api.models.WithKey'
    (java-mixin): |
      public static com.commercetools.api.models.common.ReferenceTypeId referenceTypeId() {
          return com.commercetools.api.models.common.ReferenceTypeId.ZONE;
      }

      default boolean contains(final String countryCode) {
          return getLocations().stream().anyMatch(location -> location.getCountry().equals(countryCode));
      }
  ZoneDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  ZonePagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Zone>'
  ZoneReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<Zone>'
  ZoneResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<Zone>'
  ZoneUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<ZoneUpdate,
      ZoneUpdateAction, ZoneUpdateBuilder>'
  ZoneUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<ZoneUpdateAction>'
  CentPrecisionMoney:
    (java-mixin): |
      public static CentPrecisionMoney of(final javax.money.MonetaryAmount monetaryAmount) {
          return MoneyUtil.of(monetaryAmount);
      }
      public default CentPrecisionMoneyDraft toDraft() {
          return CentPrecisionMoneyDraft.of(this);
      }
  CentPrecisionMoneyDraft:
    (java-mixin): |
      public static CentPrecisionMoneyDraft of(final javax.money.MonetaryAmount monetaryAmount) {
          return MoneyUtil.draftOf(monetaryAmount);
      }
      public static CentPrecisionMoneyDraft of(final CentPrecisionMoney template) {
          CentPrecisionMoneyDraftImpl instance = new CentPrecisionMoneyDraftImpl();
          instance.setCentAmount(template.getCentAmount());
          instance.setCurrencyCode(template.getCurrencyCode());
          instance.setFractionDigits(template.getFractionDigits());
          return instance;
      }
  HighPrecisionMoney:
    (java-mixin): |
      public static HighPrecisionMoney of(final javax.money.MonetaryAmount monetaryAmount, final int fractionDigits) {
          return MoneyUtil.of(monetaryAmount, fractionDigits);
      }
      public default HighPrecisionMoneyDraft toDraft() {
          return HighPrecisionMoneyDraft.of(this);
      }
      @Override
      default javax.money.MonetaryOperator createMoneyOperator() {
          return amount -> MoneyUtil.of(amount, getFractionDigits());
      }
  HighPrecisionMoneyDraft:
    (java-mixin): |
      public static HighPrecisionMoneyDraft of(javax.money.MonetaryAmount monetaryAmount, final int fractionDigits) {
          return MoneyUtil.draftOf(monetaryAmount, fractionDigits);
      }
      public static HighPrecisionMoneyDraft of(final HighPrecisionMoney template) {
          HighPrecisionMoneyDraftImpl instance = new HighPrecisionMoneyDraftImpl();
          instance.setCentAmount(template.getCentAmount());
          instance.setCurrencyCode(template.getCurrencyCode());
          instance.setFractionDigits(template.getFractionDigits());
          instance.setPreciseAmount(template.getPreciseAmount());
          return instance;
      }
      @Override
      default javax.money.MonetaryOperator createMoneyOperator() {
          return amount -> MoneyUtil.draftOf(amount, getFractionDigits());
      }
  TypedMoney:
    (java-mixin): |
      @Override
      default javax.money.MonetaryOperator createMoneyOperator() {
          return MoneyUtil::of;
      }
  TypedMoneyDraft:
    (java-mixin): |
      @Override
      default javax.money.MonetaryOperator createMoneyOperator() {
          return MoneyUtil::draftOf;
      }
  Money:
    (java-extends): 'com.commercetools.api.models.common.MonetaryAmountConvertable'
    (java-mixin): |
      public default TypedMoneyDraft toDraft() {
          if (this instanceof TypedMoneyDraft) {
              return (TypedMoneyDraft) this;
          }
          return TypedMoneyDraft.centPrecisionBuilder()
                  .centAmount(this.getCentAmount())
                  .currencyCode(this.getCurrencyCode())
                  .build();
      }
  Reference:
    (java-extends): 'ReferenceMixin'
  KeyReference:
    (java-extends): 'com.commercetools.api.models.WithKey'
  ResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.WithKey'
  TypeReference:
    (java-extends): com.commercetools.api.models.Identifiable<Type>
    (java-mixin): |
      @Override
      public default TypeResourceIdentifier toResourceIdentifier() {
          return TypeResourceIdentifier.builder().id(this.getId()).build();
      }
  CustomFields:
    (java-extends): 'CustomFieldsMixin'
  CustomFieldsDraft:
    (java-mixin): |
      public static CustomFieldsDraft of(final CustomFields template) {
          return template.toDraft();
      }

      public static CustomFieldsDraftBuilder builder(final CustomFields template) {
          return template.toDraftBuilder();
      }
  Parcel:
    (java-extends): 'com.commercetools.api.models.Customizable<Parcel>'
    (java-mixin): |
      public default ParcelDraftBuilder toDraftBuilder() {
          return ParcelDraft.builder()
                  .measurements(this.getMeasurements())
                  .trackingData(this.getTrackingData())
                  .items(this.getItems())
                  .custom(this.getCustom().toDraft());
      }

      public default ParcelDraft toDraft() {
          return toDraftBuilder().build();
      }
  ParcelDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<ParcelDraft>'
  ReturnItem:
    (java-extends): 'com.commercetools.api.models.Customizable<ReturnItem>'
  ReturnItemDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<ReturnItemDraft>'
  Delivery:
    (java-extends): 'com.commercetools.api.models.Customizable<Delivery>'
    (java-mixin): |
      public default DeliveryDraftBuilder toDraftBuilder() {
          return DeliveryDraft.builder()
                  .address(this.getAddress().toDraft())
                  .items(this.getItems())
                  .parcels(this.getParcels().stream().map(Parcel::toDraft).collect(java.util.stream.Collectors.toList()))
                  .custom(this.getCustom().toDraft());
      }

      public default DeliveryDraft toDraft() {
          return toDraftBuilder().build();
      }
  DeliveryDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<DeliveryDraft>'
  TrackingData:
    (java-extends): 'com.commercetools.api.models.Customizable<TrackingData>'
    (java-mixin): |
        default TrackingData withTrackingId(javax.annotation.Nullable final String trackingId) {
            return TrackingDataBuilder.of(this).trackingId(trackingId).build();
        }

        default TrackingData withCarrier(javax.annotation.Nullable final String carrier) {
            return TrackingDataBuilder.of(this).carrier(carrier).build();
        }

        default TrackingData withProvider(javax.annotation.Nullable final String provider) {
            return TrackingDataBuilder.of(this).provider(provider).build();
        }

        default TrackingData withProviderTransaction(javax.annotation.Nullable final String providerTransaction) {
            return TrackingDataBuilder.of(this).providerTransaction(providerTransaction).build();
        }

        default TrackingData withIsReturn(final boolean isReturn) {
            return TrackingDataBuilder.of(this).isReturn(isReturn).build();
        }
  ApiClientPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<ApiClient>'
  AttributeGroup:
    (java-extends): 'com.commercetools.api.models.DomainResource<AttributeGroup>, com.commercetools.api.models.WithKey'
  AttributeGroupDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  AttributeReference:
    (java-extends): 'com.commercetools.api.models.WithKey'
  AttributeGroupReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<AttributeGroup>'
  AttributeGroupResourceIdentifier:
    (java-extends): com.commercetools.api.models.Identifiable<AttributeGroup>
  AttributeGroupPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<AttributeGroup>'
  AttributeGroupUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<AttributeGroupUpdate,
      AttributeGroupUpdateAction, AttributeGroupUpdateBuilder>'
  AttributeGroupUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<AttributeGroupUpdateAction>'
  BusinessUnit:
    (java-extends): 'com.commercetools.api.models.WithKey'
  BusinessUnitDraft:
    (java-extends): 'com.commercetools.api.models.WithKey'
  BusinessUnitPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<BusinessUnit>'
  BusinessUnitReference:
    (java-extends): com.commercetools.api.models.Identifiable<BusinessUnit>
  BusinessUnitResourceIdentifier:
    (java-extends): com.commercetools.api.models.Identifiable<BusinessUnit>
  BusinessUnitUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<  BusinessUnitUpdate,
      BusinessUnitUpdateAction, BusinessUnitUpdateBuilder>'
  BusinessUnitUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<BusinessUnitUpdateAction>'
  CartDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<CartDraft>, com.commercetools.api.models.WithKey'
  CartPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Cart>'
  CartReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<Cart>'
  CartResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<Cart>'
  CartUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<CartUpdate, CartUpdateAction, CartUpdateBuilder>'
  CartUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<CartUpdateAction>'
  CategoryDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<CategoryDraft>, com.commercetools.api.models.WithKey'
  CategoryPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Category>'
  CategoryReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<Category>'
  CategoryResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<Category>'

  CategoryUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<CategoryUpdate,
      CategoryUpdateAction, CategoryUpdateBuilder>'
  CategoryUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<CategoryUpdateAction>'
  CartDiscountDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<CartDiscountDraft>, com.commercetools.api.models.WithKey'
  CartDiscountPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<CartDiscount>'
  CartDiscountReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<CartDiscount>'
  CartDiscountResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<CartDiscount>'
  CartDiscountUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<CartDiscountUpdate,
      CartDiscountUpdateAction, CartDiscountUpdateBuilder>'
  CartDiscountUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<CartDiscountUpdateAction>'
  CartAddCustomLineItemAction:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<CartAddCustomLineItemAction>'
  CartAddLineItemAction:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<CartAddLineItemAction>'
  ChannelDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<ChannelDraft>, com.commercetools.api.models.WithKey'
  ChannelPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Channel>'
  ChannelReference:
    (java-extends): 'com.commercetools.api.models.Identifiable<Channel>'
  ChannelResourceIdentifier:
    (java-extends): 'com.commercetools.api.models.Identifiable<Channel>'
  ChannelUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<ChannelUpdate,
      ChannelUpdateAction, ChannelUpdateBuilder>'
  ChannelUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<ChannelUpdateAction>'

  CustomLineItem:
    (java-extends): 'com.commercetools.api.models.Customizable<CustomLineItem>'
  CustomLineItemDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<CustomLineItemDraft>'
  CustomLineItemImportDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<CustomLineItemImportDraft>'
  Update:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<Update, UpdateAction, UpdateBuilder>'
  UpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<UpdateAction>'
  OrderEditDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<OrderEditDraft>, com.commercetools.api.models.WithKey'
  PagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<BaseResource>'
  LineItem:
    (java-extends): 'com.commercetools.api.models.Customizable<LineItem>'
  LineItemDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<LineItemDraft>'
  LineItemImportDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<LineItemImportDraft>'

  MessagePagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<Message>'
  Message:
    (java-extends): 'com.commercetools.api.models.DomainResource<Message>'
  MyPaymentPagedQueryResponse:
    (java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<MyPayment>'
  MyCartDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<MyCartDraft>'
  MyCartUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<MyCartUpdate, MyCartUpdateAction, MyCartUpdateBuilder>'
  MyCartUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<MyCartUpdateAction>'
  MyCartAddLineItemAction:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<MyCartAddLineItemAction>'
  MyCustomerDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<MyCustomerDraft>'
  MyPayment:
    (java-extends): 'com.commercetools.api.models.DomainResource<MyPayment>, com.commercetools.api.models.Customizable<MyPayment>'
  MyPaymentDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<MyPaymentDraft>'
  MyPaymentUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<MyPaymentUpdate,
      MyPaymentUpdateAction, MyPaymentUpdateBuilder>'
  MyPaymentUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<MyPaymentUpdateAction>'
  MyShoppingListDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<MyShoppingListDraft>'
  MyShoppingListUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<MyShoppingListUpdate,
      MyShoppingListUpdateAction, MyShoppingListUpdateBuilder>'
  MyShoppingListUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<MyShoppingListUpdateAction>'
  MyShoppingListAddLineItemAction:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<MyShoppingListAddLineItemAction>'
  MyShoppingListAddTextLineItemAction:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<MyShoppingListAddTextLineItemAction>'
  MyTransactionDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<MyTransactionDraft>'
  MyQuoteUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<MyQuoteUpdate, MyQuoteUpdateAction, MyQuoteUpdateBuilder>'
  MyQuoteUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<MyQuoteUpdateAction>'
  MyQuoteRequestUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<MyQuoteRequestUpdate,
      MyQuoteRequestUpdateAction, MyQuoteRequestUpdateBuilder>'
  MyQuoteRequestUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<MyQuoteRequestUpdateAction>'
  MyCustomerUpdate:
    (java-extends): 'com.commercetools.api.models.ResourceUpdate<MyCustomerUpdate,
      MyCustomerUpdateAction, MyCustomerUpdateBuilder>'
  MyCustomerUpdateAction:
    (java-extends): 'com.commercetools.api.models.ResourceUpdateAction<MyCustomerUpdateAction>'
  MyLineItemDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<MyLineItemDraft>'
  Price:
    (java-extends): 'com.commercetools.api.models.Customizable<Price>, com.commercetools.api.models.WithKey'
  PriceDraft:
    (java-extends): 'com.commercetools.api.models.CustomizableDraft<PriceDraft>, com.commercetools.api.models.WithKey'
  QueryPrice:
    (java-extends): 'com.commercetools.api.models.Customizable<QueryPrice>'
  ScopedPrice:
    (java-extends): 'com.commercetools.api.models.Customizable<ScopedPrice>'
  MyBusinessUnitDraft:
    (java-extends): 'com.commercetools.api.models.Customizable<MyBusinessUnitDraft>, com.commercetools.api.models.WithKey'
/{projectKey}:
  /categories:
    (java-implements): 'ByProjectKeyCategoriesRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyCategoriesGet,
        com.commercetools.api.models.category.CategoryPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyCategoriesKeyByKeyDelete, com.commercetools.api.models.category.Category>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyCategoriesByIDDelete, com.commercetools.api.models.category.Category>'
  /carts:
    (java-implements): 'ByProjectKeyCartsRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyCartsGet,
        com.commercetools.api.models.cart.CartPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyCartsKeyByKeyDelete, com.commercetools.api.models.cart.Cart>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyCartsByIDDelete, com.commercetools.api.models.cart.Cart>'

  /cart-discounts:
    (java-implements): 'ByProjectKeyCartDiscountsRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyCartDiscountsGet,
        com.commercetools.api.models.cart_discount.CartDiscountPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyCartDiscountsKeyByKeyDelete, com.commercetools.api.models.cart_discount.CartDiscount>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyCartDiscountsByIDDelete, com.commercetools.api.models.cart_discount.CartDiscount>'

  /channels:
    (java-implements): 'ByProjectKeyChannelsRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyChannelsGet,
        com.commercetools.api.models.channel.ChannelPagedQueryResponse>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyChannelsByIDDelete, com.commercetools.api.models.channel.Channel>'

  /customers:
    (java-implements): 'ByProjectKeyCustomersRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyCustomersGet,
        com.commercetools.api.models.customer.CustomerPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyCustomersKeyByKeyDelete, com.commercetools.api.models.customer.Customer>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyCustomersByIDDelete, com.commercetools.api.models.customer.Customer>'

  /custom-objects:
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyCustomObjectsGet,
        com.commercetools.api.models.custom_object.CustomObjectPagedQueryResponse>'
  /customer-groups:
    (java-implements): 'ByProjectKeyCustomerGroupsRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyCustomerGroupsGet,
        com.commercetools.api.models.customer_group.CustomerGroupPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyCustomerGroupsKeyByKeyDelete, com.commercetools.api.models.customer_group.CustomerGroup>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyCustomerGroupsByIDDelete, com.commercetools.api.models.customer_group.CustomerGroup>'

  /discount-codes:
    (java-implements): 'ByProjectKeyDiscountCodesRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyDiscountCodesGet,
        com.commercetools.api.models.discount_code.DiscountCodePagedQueryResponse>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyDiscountCodesByIDDelete, com.commercetools.api.models.discount_code.DiscountCode>'

  /in-store/key={storeKey}:
    /me:
      /shopping-lists:
        get:
          (java-implements):
            'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyInStoreKeyByStoreKeyMeShoppingListsGet,
            com.commercetools.api.models.shopping_list.ShoppingListPagedQueryResponse>'
    /shopping-lists:
      get:
        (java-implements):
          'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyInStoreKeyByStoreKeyShoppingListsGet,
          com.commercetools.api.models.shopping_list.ShoppingListPagedQueryResponse>'
  /inventory:
    (java-implements): 'ByProjectKeyInventoryRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyInventoryGet,
        com.commercetools.api.models.inventory.InventoryPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyInventoryKeyByKeyDelete, com.commercetools.api.models.inventory.InventoryEntry>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyInventoryByIDDelete, com.commercetools.api.models.inventory.InventoryEntry>'

  /messages:
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyMessagesGet,
        com.commercetools.api.models.message.MessagePagedQueryResponse>'
  /orders:
    (java-implements): 'ByProjectKeyOrdersRequestBuilderMixin'
    /edits:
      get:
        (java-implements):
          'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyOrdersEditsGet,
          com.commercetools.api.models.order_edit.OrderEditPagedQueryResponse>'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyOrdersGet,
        com.commercetools.api.models.order.OrderPagedQueryResponse>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyOrdersByIDDelete, com.commercetools.api.models.order.Order>'

  /payments:
    (java-implements): 'ByProjectKeyPaymentsRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyPaymentsGet,
        com.commercetools.api.models.payment.PaymentPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyPaymentsKeyByKeyDelete, com.commercetools.api.models.payment.Payment>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyPaymentsByIDDelete, com.commercetools.api.models.payment.Payment>'

  /products:
    (java-implements): 'ByProjectKeyProductsRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyProductsGet,
        com.commercetools.api.models.product.ProductPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyProductsKeyByKeyDelete, com.commercetools.api.models.product.Product>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyProductsByIDDelete, com.commercetools.api.models.product.Product>'

  /product-discounts:
    (java-implements): 'ByProjectKeyProductDiscountsRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyProductDiscountsGet,
        com.commercetools.api.models.product_discount.ProductDiscountPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyProductDiscountsKeyByKeyDelete, com.commercetools.api.models.product_discount.ProductDiscount>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyProductDiscountsByIDDelete, com.commercetools.api.models.product_discount.ProductDiscount>'

  /product-projections:
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyProductProjectionsGet,
        com.commercetools.api.models.product.ProductProjectionPagedQueryResponse>'
  /product-types:
    (java-implements): 'ByProjectKeyProductTypesRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyProductTypesGet,
        com.commercetools.api.models.product_type.ProductTypePagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyProductTypesKeyByKeyDelete, com.commercetools.api.models.product_type.ProductType>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyProductTypesByIDDelete, com.commercetools.api.models.product_type.ProductType>'
  /quotes:
    (java-implements): 'ByProjectKeyQuotesRequestBuilderMixin'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyQuotesKeyByKeyDelete, com.commercetools.api.models.quote.Quote>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyQuotesByIDDelete, com.commercetools.api.models.quote.Quote>'

  /quote-requests:
    (java-implements): 'ByProjectKeyQuoteRequestsRequestBuilderMixin'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyQuoteRequestsKeyByKeyDelete, com.commercetools.api.models.quote_request.QuoteRequest>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyQuoteRequestsByIDDelete, com.commercetools.api.models.quote_request.QuoteRequest>'

  /staged-quotes:
    (java-implements): 'ByProjectKeyStagedQuotesRequestBuilderMixin'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyStagedQuotesKeyByKeyDelete, com.commercetools.api.models.staged_quote.StagedQuote>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyStagedQuotesByIDDelete, com.commercetools.api.models.staged_quote.StagedQuote>'

  /reviews:
    (java-implements): 'ByProjectKeyReviewsRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyReviewsGet,
        com.commercetools.api.models.review.ReviewPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyReviewsKeyByKeyDelete, com.commercetools.api.models.review.Review>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyReviewsByIDDelete, com.commercetools.api.models.review.Review>'

  /shipping-methods:
    (java-implements): 'ByProjectKeyShippingMethodsRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyShippingMethodsGet,
        com.commercetools.api.models.shipping_method.ShippingMethodPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyShippingMethodsKeyByKeyDelete, com.commercetools.api.models.shipping_method.ShippingMethod>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyShippingMethodsByIDDelete, com.commercetools.api.models.shipping_method.ShippingMethod>'

  /shopping-lists:
    (java-implements): 'ByProjectKeyShoppingListsRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyShoppingListsGet,
        com.commercetools.api.models.shopping_list.ShoppingListPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyShoppingListsKeyByKeyDelete, com.commercetools.api.models.shopping_list.ShoppingList>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyShoppingListsByIDDelete, com.commercetools.api.models.shopping_list.ShoppingList>'

  /states:
    (java-implements): 'ByProjectKeyStatesRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyStatesGet,
        com.commercetools.api.models.state.StatePagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyStatesKeyByKeyDelete, com.commercetools.api.models.state.State>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyStatesByIDDelete, com.commercetools.api.models.state.State>'

  /subscriptions:
    (java-implements): 'ByProjectKeySubscriptionsRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeySubscriptionsGet,
        com.commercetools.api.models.subscription.SubscriptionPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeySubscriptionsKeyByKeyDelete, com.commercetools.api.models.subscription.Subscription>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeySubscriptionsByIDDelete, com.commercetools.api.models.subscription.Subscription>'

  /tax-categories:
    (java-implements): 'ByProjectKeyTaxCategoriesRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyTaxCategoriesGet,
        com.commercetools.api.models.tax_category.TaxCategoryPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyTaxCategoriesKeyByKeyDelete, com.commercetools.api.models.tax_category.TaxCategory>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyTaxCategoriesByIDDelete, com.commercetools.api.models.tax_category.TaxCategory>'

  /types:
    (java-implements): 'ByProjectKeyTypesRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyTypesGet,
        com.commercetools.api.models.type.TypePagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyTypesKeyByKeyDelete, com.commercetools.api.models.type.Type>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyTypesByIDDelete, com.commercetools.api.models.type.Type>'

  /zones:
    (java-implements): 'ByProjectKeyZonesRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyZonesGet,
        com.commercetools.api.models.zone.ZonePagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyZonesKeyByKeyDelete, com.commercetools.api.models.zone.Zone>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyZonesByIDDelete, com.commercetools.api.models.zone.Zone>'

  /extensions:
    (java-implements): 'ByProjectKeyExtensionsRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyExtensionsGet,
        com.commercetools.api.models.extension.ExtensionPagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyExtensionsKeyByKeyDelete, com.commercetools.api.models.extension.Extension>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyExtensionsByIDDelete, com.commercetools.api.models.extension.Extension>'

  /stores:
    (java-implements): 'ByProjectKeyStoresRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyStoresGet,
        com.commercetools.api.models.store.StorePagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyStoresKeyByKeyDelete, com.commercetools.api.models.store.Store>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyStoresByIDDelete, com.commercetools.api.models.store.Store>'

  /standalone-prices:
    (java-implements): 'ByProjectKeyStandalonePricesRequestBuilderMixin'
    get:
      (java-implements):
        'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyStandalonePricesGet,
        com.commercetools.api.models.standalone_price.StandalonePricePagedQueryResponse>'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyStandalonePricesKeyByKeyDelete, com.commercetools.api.models.standalone_price.StandalonePrice>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyStandalonePricesByIDDelete, com.commercetools.api.models.standalone_price.StandalonePrice>'

  /attribute-groups:
    (java-implements): 'ByProjectKeyAttributeGroupsRequestBuilderMixin'
    /key={key}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyAttributeGroupsKeyByKeyDelete, com.commercetools.api.models.attribute_group.AttributeGroup>'
    /{ID}:
      delete:
        (java-implements):
          'com.commercetools.api.client.ApiDeleteMethod<ByProjectKeyAttributeGroupsByIDDelete, com.commercetools.api.models.attribute_group.AttributeGroup>'

  /api-clients:
    (java-implements): 'ByProjectKeyApiClientsRequestBuilderMixin'
