
dependencies {
    api project(":rmf:rmf-java-base")
    api "org.asynchttpclient:async-http-client:2.16.1"
    api 'commons-io:commons-io:2.22.0' version {
        strictly '[2.8.0,)'
        prefer '2.22.0'
    }
    api "io.netty:netty-codec:4.2.17.Final"
    api "io.netty:netty-codec-http:4.2.17.Final"
    api "io.netty:netty-codec-socks:4.2.17.Final"
    api "io.netty:netty-handler-proxy:4.2.17.Final"
    api "io.netty:netty-handler:4.2.17.Final"
    implementation 'jakarta.validation:jakarta.validation-api:3.1.1'
}
