
package com.commercetools.api.models.message;

import java.time.*;
import java.util.*;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.*;

import io.vrap.rmf.base.client.ModelBase;
import io.vrap.rmf.base.client.utils.Generated;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 *  <p>Generated by a successful <a href="https://docs.commercetools.com/apis/ctp:api:type:StoreAddProductSelectionAction" rel="nofollow">Add Product Selection</a>, <a href="https://docs.commercetools.com/apis/ctp:api:type:StoreRemoveProductSelectionAction" rel="nofollow">Remove Product Selection</a>, <a href="https://docs.commercetools.com/apis/ctp:api:type:StoreSetProductSelectionsAction" rel="nofollow">Set Product Selections</a>, or <a href="https://docs.commercetools.com/apis/ctp:api:type:StoreChangeProductSelectionAction" rel="nofollow">Change Product Selections Active</a> update action.</p>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
public class StoreProductSelectionsChangedMessagePayloadImpl
        implements StoreProductSelectionsChangedMessagePayload, ModelBase {

    private String type;

    private java.util.List<com.commercetools.api.models.store.ProductSelectionSetting> addedProductSelections;

    private java.util.List<com.commercetools.api.models.store.ProductSelectionSetting> removedProductSelections;

    private java.util.List<com.commercetools.api.models.store.ProductSelectionSetting> updatedProductSelections;

    /**
     * create instance with all properties
     */
    @JsonCreator
    StoreProductSelectionsChangedMessagePayloadImpl(
            @JsonProperty("addedProductSelections") final java.util.List<com.commercetools.api.models.store.ProductSelectionSetting> addedProductSelections,
            @JsonProperty("removedProductSelections") final java.util.List<com.commercetools.api.models.store.ProductSelectionSetting> removedProductSelections,
            @JsonProperty("updatedProductSelections") final java.util.List<com.commercetools.api.models.store.ProductSelectionSetting> updatedProductSelections) {
        this.addedProductSelections = addedProductSelections;
        this.removedProductSelections = removedProductSelections;
        this.updatedProductSelections = updatedProductSelections;
        this.type = STORE_PRODUCT_SELECTIONS_CHANGED;
    }

    /**
     * create empty instance
     */
    public StoreProductSelectionsChangedMessagePayloadImpl() {
        this.type = STORE_PRODUCT_SELECTIONS_CHANGED;
    }

    /**
     *
     */

    public String getType() {
        return this.type;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:ProductSelectionSetting" rel="nofollow">ProductSelectionSettings</a> that were added to the <a href="https://docs.commercetools.com/apis/ctp:api:type:Store" rel="nofollow">Store</a>.</p>
     */

    public java.util.List<com.commercetools.api.models.store.ProductSelectionSetting> getAddedProductSelections() {
        return this.addedProductSelections;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:ProductSelectionSetting" rel="nofollow">ProductSelectionSettings</a> that were removed from the <a href="https://docs.commercetools.com/apis/ctp:api:type:Store" rel="nofollow">Store</a>.</p>
     */

    public java.util.List<com.commercetools.api.models.store.ProductSelectionSetting> getRemovedProductSelections() {
        return this.removedProductSelections;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:ProductSelectionSetting" rel="nofollow">ProductSelectionSettings</a> that were updated in the <a href="https://docs.commercetools.com/apis/ctp:api:type:Store" rel="nofollow">Store</a>.</p>
     */

    public java.util.List<com.commercetools.api.models.store.ProductSelectionSetting> getUpdatedProductSelections() {
        return this.updatedProductSelections;
    }

    public void setAddedProductSelections(
            final com.commercetools.api.models.store.ProductSelectionSetting... addedProductSelections) {
        this.addedProductSelections = new ArrayList<>(Arrays.asList(addedProductSelections));
    }

    public void setAddedProductSelections(
            final java.util.List<com.commercetools.api.models.store.ProductSelectionSetting> addedProductSelections) {
        this.addedProductSelections = addedProductSelections;
    }

    public void setRemovedProductSelections(
            final com.commercetools.api.models.store.ProductSelectionSetting... removedProductSelections) {
        this.removedProductSelections = new ArrayList<>(Arrays.asList(removedProductSelections));
    }

    public void setRemovedProductSelections(
            final java.util.List<com.commercetools.api.models.store.ProductSelectionSetting> removedProductSelections) {
        this.removedProductSelections = removedProductSelections;
    }

    public void setUpdatedProductSelections(
            final com.commercetools.api.models.store.ProductSelectionSetting... updatedProductSelections) {
        this.updatedProductSelections = new ArrayList<>(Arrays.asList(updatedProductSelections));
    }

    public void setUpdatedProductSelections(
            final java.util.List<com.commercetools.api.models.store.ProductSelectionSetting> updatedProductSelections) {
        this.updatedProductSelections = updatedProductSelections;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;

        if (o == null || getClass() != o.getClass())
            return false;

        StoreProductSelectionsChangedMessagePayloadImpl that = (StoreProductSelectionsChangedMessagePayloadImpl) o;

        return new EqualsBuilder().append(type, that.type)
                .append(addedProductSelections, that.addedProductSelections)
                .append(removedProductSelections, that.removedProductSelections)
                .append(updatedProductSelections, that.updatedProductSelections)
                .append(type, that.type)
                .append(addedProductSelections, that.addedProductSelections)
                .append(removedProductSelections, that.removedProductSelections)
                .append(updatedProductSelections, that.updatedProductSelections)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37).append(type)
                .append(addedProductSelections)
                .append(removedProductSelections)
                .append(updatedProductSelections)
                .toHashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE).append("type", type)
                .append("addedProductSelections", addedProductSelections)
                .append("removedProductSelections", removedProductSelections)
                .append("updatedProductSelections", updatedProductSelections)
                .build();
    }

    @Override
    public StoreProductSelectionsChangedMessagePayload copyDeep() {
        return StoreProductSelectionsChangedMessagePayload.deepCopy(this);
    }
}
