
dependencies {
    implementation 'com.google.code.findbugs:jsr305:3.0.2'
    api 'tools.jackson.core:jackson-databind:3.2.2'
    api 'tools.jackson.core:jackson-core:3.2.2'
//    api jackson_core.datatype
    api 'org.apache.commons:commons-lang3:3.20.0'
    api 'org.slf4j:slf4j-api:2.0.18'
    api 'dev.failsafe:failsafe:3.3.2'
    api "com.spotify:completable-futures:0.3.6"
    api "org.reflections:reflections:0.10.2"
}


sourceSets {
    main {
        java {
            srcDir 'build/generated/src/main/java'
        }
    }
}


tasks.register('versionTxt') {
    doLast {
        new File(projectDir, "$buildInfoPath/io/vrap/rmf/base/client").mkdirs()
        new File(projectDir, "$buildInfoPath/io/vrap/rmf/base/client/BuildInfo.java").text = """
package io.vrap.rmf.base.client;

public class BuildInfo {
    public static final String VERSION = "$version";
}
"""
    }
}

compileJava{
    dependsOn versionTxt
}
