
package com.commercetools.checkout.models.recurring_payment_job;

import java.time.*;
import java.util.*;
import java.util.function.Function;

import javax.annotation.Nullable;

import com.commercetools.checkout.models.common.PaymentMethodReference;
import com.commercetools.checkout.models.payment.PaymentReference;
import com.fasterxml.jackson.annotation.*;

import io.vrap.rmf.base.client.utils.Generated;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import tools.jackson.databind.annotation.*;

/**
 *  <p>Draft type to create a <a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPaymentJob" rel="nofollow">RecurringPaymentJob</a>.</p>
 *
 * <hr>
 * Example to create an instance using the builder pattern
 * <div class=code-example>
 * <pre><code class='java'>
 *     RecurringPaymentJobDraft recurringPaymentJobDraft = RecurringPaymentJobDraft.builder()
 *             .originPayment(originPaymentBuilder -> originPaymentBuilder)
 *             .paymentMethod(paymentMethodBuilder -> paymentMethodBuilder)
 *             .build()
 * </code></pre>
 * </div>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
@JsonDeserialize(as = RecurringPaymentJobDraftImpl.class)
public interface RecurringPaymentJobDraft extends io.vrap.rmf.base.client.Draft<RecurringPaymentJobDraft> {

    /**
     *  <p>User-defined unique identifier of the Recurring Payment Job.</p>
     * @return key
     */

    @JsonProperty("key")
    public String getKey();

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generates the <span>Recurring Order</span>.</p>
     * @return originPayment
     */
    @NotNull
    @Valid
    @JsonProperty("originPayment")
    public PaymentReference getOriginPayment();

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     * @return paymentMethod
     */
    @NotNull
    @Valid
    @JsonProperty("paymentMethod")
    public PaymentMethodReference getPaymentMethod();

    /**
     *  <p>User-defined unique identifier of the Recurring Payment Job.</p>
     * @param key value to be set
     */

    public void setKey(final String key);

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generates the <span>Recurring Order</span>.</p>
     * @param originPayment value to be set
     */

    public void setOriginPayment(final PaymentReference originPayment);

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     * @param paymentMethod value to be set
     */

    public void setPaymentMethod(final PaymentMethodReference paymentMethod);

    /**
     * factory method
     * @return instance of RecurringPaymentJobDraft
     */
    public static RecurringPaymentJobDraft of() {
        return new RecurringPaymentJobDraftImpl();
    }

    /**
     * factory method to create a shallow copy RecurringPaymentJobDraft
     * @param template instance to be copied
     * @return copy instance
     */
    public static RecurringPaymentJobDraft of(final RecurringPaymentJobDraft template) {
        RecurringPaymentJobDraftImpl instance = new RecurringPaymentJobDraftImpl();
        instance.setKey(template.getKey());
        instance.setOriginPayment(template.getOriginPayment());
        instance.setPaymentMethod(template.getPaymentMethod());
        return instance;
    }

    public RecurringPaymentJobDraft copyDeep();

    /**
     * factory method to create a deep copy of RecurringPaymentJobDraft
     * @param template instance to be copied
     * @return copy instance
     */
    @Nullable
    public static RecurringPaymentJobDraft deepCopy(@Nullable final RecurringPaymentJobDraft template) {
        if (template == null) {
            return null;
        }
        RecurringPaymentJobDraftImpl instance = new RecurringPaymentJobDraftImpl();
        instance.setKey(template.getKey());
        instance.setOriginPayment(
            com.commercetools.checkout.models.payment.PaymentReference.deepCopy(template.getOriginPayment()));
        instance.setPaymentMethod(
            com.commercetools.checkout.models.common.PaymentMethodReference.deepCopy(template.getPaymentMethod()));
        return instance;
    }

    /**
     * builder factory method for RecurringPaymentJobDraft
     * @return builder
     */
    public static RecurringPaymentJobDraftBuilder builder() {
        return RecurringPaymentJobDraftBuilder.of();
    }

    /**
     * create builder for RecurringPaymentJobDraft instance
     * @param template instance with prefilled values for the builder
     * @return builder
     */
    public static RecurringPaymentJobDraftBuilder builder(final RecurringPaymentJobDraft template) {
        return RecurringPaymentJobDraftBuilder.of(template);
    }

    /**
     * accessor map function
     * @param <T> mapped type
     * @param helper function to map the object
     * @return mapped value
     */
    default <T> T withRecurringPaymentJobDraft(Function<RecurringPaymentJobDraft, T> helper) {
        return helper.apply(this);
    }

    /**
     * gives a TypeReference for usage with Jackson DataBind
     * @return TypeReference
     */
    public static tools.jackson.core.type.TypeReference<RecurringPaymentJobDraft> typeReference() {
        return new tools.jackson.core.type.TypeReference<RecurringPaymentJobDraft>() {
            @Override
            public String toString() {
                return "TypeReference<RecurringPaymentJobDraft>";
            }
        };
    }
}
