
package com.commercetools.checkout.models.recurring_payment_job;

import java.util.*;
import java.util.function.Function;

import javax.annotation.Nullable;

import io.vrap.rmf.base.client.Builder;
import io.vrap.rmf.base.client.utils.Generated;

/**
 * RecurringPaymentJobBuilder
 * <hr>
 * Example to create an instance using the builder pattern
 * <div class=code-example>
 * <pre><code class='java'>
 *     RecurringPaymentJob recurringPaymentJob = RecurringPaymentJob.builder()
 *             .id("{id}")
 *             .version(1)
 *             .originPayment(originPaymentBuilder -> originPaymentBuilder)
 *             .paymentMethod(paymentMethodBuilder -> paymentMethodBuilder)
 *             .status(statusBuilder -> statusBuilder)
 *             .createdAt(ZonedDateTime.parse("2022-01-01T12:00:00.301Z"))
 *             .lastModifiedAt(ZonedDateTime.parse("2022-01-01T12:00:00.301Z"))
 *             .build()
 * </code></pre>
 * </div>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
public class RecurringPaymentJobBuilder implements Builder<RecurringPaymentJob> {

    private String id;

    private Integer version;

    @Nullable
    private String key;

    private com.commercetools.checkout.models.payment.PaymentReference originPayment;

    private com.commercetools.checkout.models.common.PaymentMethodReference paymentMethod;

    @Nullable
    private java.util.List<com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference> recurringPayments;

    private com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatus status;

    private java.time.ZonedDateTime createdAt;

    private java.time.ZonedDateTime lastModifiedAt;

    /**
     *  <p>Unique identifier of the Recurring Payment Job.</p>
     * @param id value to be set
     * @return Builder
     */

    public RecurringPaymentJobBuilder id(final String id) {
        this.id = id;
        return this;
    }

    /**
     *  <p>Current version of the Recurring Payment Job.</p>
     * @param version value to be set
     * @return Builder
     */

    public RecurringPaymentJobBuilder version(final Integer version) {
        this.version = version;
        return this;
    }

    /**
     *  <p>User-defined unique identifier of the Recurring Payment Job.</p>
     * @param key value to be set
     * @return Builder
     */

    public RecurringPaymentJobBuilder key(@Nullable final String key) {
        this.key = key;
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generated the <span>Recurring Order</span>.</p>
     * @param builder function to build the originPayment value
     * @return Builder
     */

    public RecurringPaymentJobBuilder originPayment(
            Function<com.commercetools.checkout.models.payment.PaymentReferenceBuilder, com.commercetools.checkout.models.payment.PaymentReferenceBuilder> builder) {
        this.originPayment = builder.apply(com.commercetools.checkout.models.payment.PaymentReferenceBuilder.of())
                .build();
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generated the <span>Recurring Order</span>.</p>
     * @param builder function to build the originPayment value
     * @return Builder
     */

    public RecurringPaymentJobBuilder withOriginPayment(
            Function<com.commercetools.checkout.models.payment.PaymentReferenceBuilder, com.commercetools.checkout.models.payment.PaymentReference> builder) {
        this.originPayment = builder.apply(com.commercetools.checkout.models.payment.PaymentReferenceBuilder.of());
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generated the <span>Recurring Order</span>.</p>
     * @param originPayment value to be set
     * @return Builder
     */

    public RecurringPaymentJobBuilder originPayment(
            final com.commercetools.checkout.models.payment.PaymentReference originPayment) {
        this.originPayment = originPayment;
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     * @param builder function to build the paymentMethod value
     * @return Builder
     */

    public RecurringPaymentJobBuilder paymentMethod(
            Function<com.commercetools.checkout.models.common.PaymentMethodReferenceBuilder, com.commercetools.checkout.models.common.PaymentMethodReferenceBuilder> builder) {
        this.paymentMethod = builder.apply(com.commercetools.checkout.models.common.PaymentMethodReferenceBuilder.of())
                .build();
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     * @param builder function to build the paymentMethod value
     * @return Builder
     */

    public RecurringPaymentJobBuilder withPaymentMethod(
            Function<com.commercetools.checkout.models.common.PaymentMethodReferenceBuilder, com.commercetools.checkout.models.common.PaymentMethodReference> builder) {
        this.paymentMethod = builder.apply(com.commercetools.checkout.models.common.PaymentMethodReferenceBuilder.of());
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     * @param paymentMethod value to be set
     * @return Builder
     */

    public RecurringPaymentJobBuilder paymentMethod(
            final com.commercetools.checkout.models.common.PaymentMethodReference paymentMethod) {
        this.paymentMethod = paymentMethod;
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPayment" rel="nofollow">Recurring Payments</a> created from the Recurring Payment Job.</p>
     * @param recurringPayments value to be set
     * @return Builder
     */

    public RecurringPaymentJobBuilder recurringPayments(
            @Nullable final com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference... recurringPayments) {
        this.recurringPayments = new ArrayList<>(Arrays.asList(recurringPayments));
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPayment" rel="nofollow">Recurring Payments</a> created from the Recurring Payment Job.</p>
     * @param recurringPayments value to be set
     * @return Builder
     */

    public RecurringPaymentJobBuilder recurringPayments(
            @Nullable final java.util.List<com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference> recurringPayments) {
        this.recurringPayments = recurringPayments;
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPayment" rel="nofollow">Recurring Payments</a> created from the Recurring Payment Job.</p>
     * @param recurringPayments value to be set
     * @return Builder
     */

    public RecurringPaymentJobBuilder plusRecurringPayments(
            @Nullable final com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference... recurringPayments) {
        if (this.recurringPayments == null) {
            this.recurringPayments = new ArrayList<>();
        }
        this.recurringPayments.addAll(Arrays.asList(recurringPayments));
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPayment" rel="nofollow">Recurring Payments</a> created from the Recurring Payment Job.</p>
     * @param builder function to build the recurringPayments value
     * @return Builder
     */

    public RecurringPaymentJobBuilder plusRecurringPayments(
            Function<com.commercetools.checkout.models.recurring_payment.RecurringPaymentReferenceBuilder, com.commercetools.checkout.models.recurring_payment.RecurringPaymentReferenceBuilder> builder) {
        if (this.recurringPayments == null) {
            this.recurringPayments = new ArrayList<>();
        }
        this.recurringPayments.add(
            builder.apply(com.commercetools.checkout.models.recurring_payment.RecurringPaymentReferenceBuilder.of())
                    .build());
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPayment" rel="nofollow">Recurring Payments</a> created from the Recurring Payment Job.</p>
     * @param builder function to build the recurringPayments value
     * @return Builder
     */

    public RecurringPaymentJobBuilder withRecurringPayments(
            Function<com.commercetools.checkout.models.recurring_payment.RecurringPaymentReferenceBuilder, com.commercetools.checkout.models.recurring_payment.RecurringPaymentReferenceBuilder> builder) {
        this.recurringPayments = new ArrayList<>();
        this.recurringPayments.add(
            builder.apply(com.commercetools.checkout.models.recurring_payment.RecurringPaymentReferenceBuilder.of())
                    .build());
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPayment" rel="nofollow">Recurring Payments</a> created from the Recurring Payment Job.</p>
     * @param builder function to build the recurringPayments value
     * @return Builder
     */

    public RecurringPaymentJobBuilder addRecurringPayments(
            Function<com.commercetools.checkout.models.recurring_payment.RecurringPaymentReferenceBuilder, com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference> builder) {
        return plusRecurringPayments(
            builder.apply(com.commercetools.checkout.models.recurring_payment.RecurringPaymentReferenceBuilder.of()));
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPayment" rel="nofollow">Recurring Payments</a> created from the Recurring Payment Job.</p>
     * @param builder function to build the recurringPayments value
     * @return Builder
     */

    public RecurringPaymentJobBuilder setRecurringPayments(
            Function<com.commercetools.checkout.models.recurring_payment.RecurringPaymentReferenceBuilder, com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference> builder) {
        return recurringPayments(
            builder.apply(com.commercetools.checkout.models.recurring_payment.RecurringPaymentReferenceBuilder.of()));
    }

    /**
     *  <p>Status of the Recurring Payment Job.</p>
     * @param builder function to build the status value
     * @return Builder
     */

    public RecurringPaymentJobBuilder status(
            Function<com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatusBuilder, com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatusBuilder> builder) {
        this.status = builder
                .apply(com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatusBuilder.of())
                .build();
        return this;
    }

    /**
     *  <p>Status of the Recurring Payment Job.</p>
     * @param builder function to build the status value
     * @return Builder
     */

    public RecurringPaymentJobBuilder withStatus(
            Function<com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatusBuilder, com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatus> builder) {
        this.status = builder
                .apply(com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatusBuilder.of());
        return this;
    }

    /**
     *  <p>Status of the Recurring Payment Job.</p>
     * @param status value to be set
     * @return Builder
     */

    public RecurringPaymentJobBuilder status(
            final com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatus status) {
        this.status = status;
        return this;
    }

    /**
     *  <p>Date and time (UTC) the Recurring Payment Job was initially created.</p>
     * @param createdAt value to be set
     * @return Builder
     */

    public RecurringPaymentJobBuilder createdAt(final java.time.ZonedDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     *  <p>Date and time (UTC) the Recurring Payment Job was last updated.</p>
     * @param lastModifiedAt value to be set
     * @return Builder
     */

    public RecurringPaymentJobBuilder lastModifiedAt(final java.time.ZonedDateTime lastModifiedAt) {
        this.lastModifiedAt = lastModifiedAt;
        return this;
    }

    /**
     *  <p>Unique identifier of the Recurring Payment Job.</p>
     * @return id
     */

    public String getId() {
        return this.id;
    }

    /**
     *  <p>Current version of the Recurring Payment Job.</p>
     * @return version
     */

    public Integer getVersion() {
        return this.version;
    }

    /**
     *  <p>User-defined unique identifier of the Recurring Payment Job.</p>
     * @return key
     */

    @Nullable
    public String getKey() {
        return this.key;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generated the <span>Recurring Order</span>.</p>
     * @return originPayment
     */

    public com.commercetools.checkout.models.payment.PaymentReference getOriginPayment() {
        return this.originPayment;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     * @return paymentMethod
     */

    public com.commercetools.checkout.models.common.PaymentMethodReference getPaymentMethod() {
        return this.paymentMethod;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPayment" rel="nofollow">Recurring Payments</a> created from the Recurring Payment Job.</p>
     * @return recurringPayments
     */

    @Nullable
    public java.util.List<com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference> getRecurringPayments() {
        return this.recurringPayments;
    }

    /**
     *  <p>Status of the Recurring Payment Job.</p>
     * @return status
     */

    public com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatus getStatus() {
        return this.status;
    }

    /**
     *  <p>Date and time (UTC) the Recurring Payment Job was initially created.</p>
     * @return createdAt
     */

    public java.time.ZonedDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     *  <p>Date and time (UTC) the Recurring Payment Job was last updated.</p>
     * @return lastModifiedAt
     */

    public java.time.ZonedDateTime getLastModifiedAt() {
        return this.lastModifiedAt;
    }

    /**
     * builds RecurringPaymentJob with checking for non-null required values
     * @return RecurringPaymentJob
     */
    public RecurringPaymentJob build() {
        Objects.requireNonNull(id, RecurringPaymentJob.class + ": id is missing");
        Objects.requireNonNull(version, RecurringPaymentJob.class + ": version is missing");
        Objects.requireNonNull(originPayment, RecurringPaymentJob.class + ": originPayment is missing");
        Objects.requireNonNull(paymentMethod, RecurringPaymentJob.class + ": paymentMethod is missing");
        Objects.requireNonNull(status, RecurringPaymentJob.class + ": status is missing");
        Objects.requireNonNull(createdAt, RecurringPaymentJob.class + ": createdAt is missing");
        Objects.requireNonNull(lastModifiedAt, RecurringPaymentJob.class + ": lastModifiedAt is missing");
        return new RecurringPaymentJobImpl(id, version, key, originPayment, paymentMethod, recurringPayments, status,
            createdAt, lastModifiedAt);
    }

    /**
     * builds RecurringPaymentJob without checking for non-null required values
     * @return RecurringPaymentJob
     */
    public RecurringPaymentJob buildUnchecked() {
        return new RecurringPaymentJobImpl(id, version, key, originPayment, paymentMethod, recurringPayments, status,
            createdAt, lastModifiedAt);
    }

    /**
     * factory method for an instance of RecurringPaymentJobBuilder
     * @return builder
     */
    public static RecurringPaymentJobBuilder of() {
        return new RecurringPaymentJobBuilder();
    }

    /**
     * create builder for RecurringPaymentJob instance
     * @param template instance with prefilled values for the builder
     * @return builder
     */
    public static RecurringPaymentJobBuilder of(final RecurringPaymentJob template) {
        RecurringPaymentJobBuilder builder = new RecurringPaymentJobBuilder();
        builder.id = template.getId();
        builder.version = template.getVersion();
        builder.key = template.getKey();
        builder.originPayment = template.getOriginPayment();
        builder.paymentMethod = template.getPaymentMethod();
        builder.recurringPayments = template.getRecurringPayments();
        builder.status = template.getStatus();
        builder.createdAt = template.getCreatedAt();
        builder.lastModifiedAt = template.getLastModifiedAt();
        return builder;
    }

}
