
package com.commercetools.checkout.models.recurring_payment_job;

import java.time.*;
import java.time.ZonedDateTime;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

import javax.annotation.Nullable;

import com.commercetools.checkout.models.common.PaymentMethodReference;
import com.commercetools.checkout.models.payment.PaymentReference;
import com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference;
import com.fasterxml.jackson.annotation.*;

import io.vrap.rmf.base.client.utils.Generated;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import tools.jackson.databind.annotation.*;

/**
 *  <p>Links a <a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made through Checkout to the <a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the resulting <span>Recurring Order</span>.</p>
 *
 * <hr>
 * Example to create an instance using the builder pattern
 * <div class=code-example>
 * <pre><code class='java'>
 *     RecurringPaymentJob recurringPaymentJob = RecurringPaymentJob.builder()
 *             .id("{id}")
 *             .version(1)
 *             .originPayment(originPaymentBuilder -> originPaymentBuilder)
 *             .paymentMethod(paymentMethodBuilder -> paymentMethodBuilder)
 *             .status(statusBuilder -> statusBuilder)
 *             .createdAt(ZonedDateTime.parse("2022-01-01T12:00:00.301Z"))
 *             .lastModifiedAt(ZonedDateTime.parse("2022-01-01T12:00:00.301Z"))
 *             .build()
 * </code></pre>
 * </div>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
@JsonDeserialize(as = RecurringPaymentJobImpl.class)
public interface RecurringPaymentJob {

    /**
     *  <p>Unique identifier of the Recurring Payment Job.</p>
     * @return id
     */
    @NotNull
    @JsonProperty("id")
    public String getId();

    /**
     *  <p>Current version of the Recurring Payment Job.</p>
     * @return version
     */
    @NotNull
    @JsonProperty("version")
    public Integer getVersion();

    /**
     *  <p>User-defined unique identifier of the Recurring Payment Job.</p>
     * @return key
     */

    @JsonProperty("key")
    public String getKey();

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generated the <span>Recurring Order</span>.</p>
     * @return originPayment
     */
    @NotNull
    @Valid
    @JsonProperty("originPayment")
    public PaymentReference getOriginPayment();

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     * @return paymentMethod
     */
    @NotNull
    @Valid
    @JsonProperty("paymentMethod")
    public PaymentMethodReference getPaymentMethod();

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPayment" rel="nofollow">Recurring Payments</a> created from the Recurring Payment Job.</p>
     * @return recurringPayments
     */
    @Valid
    @JsonProperty("recurringPayments")
    public List<RecurringPaymentReference> getRecurringPayments();

    /**
     *  <p>Status of the Recurring Payment Job.</p>
     * @return status
     */
    @NotNull
    @Valid
    @JsonProperty("status")
    public RecurringPaymentJobStatus getStatus();

    /**
     *  <p>Date and time (UTC) the Recurring Payment Job was initially created.</p>
     * @return createdAt
     */
    @NotNull
    @JsonProperty("createdAt")
    public ZonedDateTime getCreatedAt();

    /**
     *  <p>Date and time (UTC) the Recurring Payment Job was last updated.</p>
     * @return lastModifiedAt
     */
    @NotNull
    @JsonProperty("lastModifiedAt")
    public ZonedDateTime getLastModifiedAt();

    /**
     *  <p>Unique identifier of the Recurring Payment Job.</p>
     * @param id value to be set
     */

    public void setId(final String id);

    /**
     *  <p>Current version of the Recurring Payment Job.</p>
     * @param version value to be set
     */

    public void setVersion(final Integer version);

    /**
     *  <p>User-defined unique identifier of the Recurring Payment Job.</p>
     * @param key value to be set
     */

    public void setKey(final String key);

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generated the <span>Recurring Order</span>.</p>
     * @param originPayment value to be set
     */

    public void setOriginPayment(final PaymentReference originPayment);

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     * @param paymentMethod value to be set
     */

    public void setPaymentMethod(final PaymentMethodReference paymentMethod);

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPayment" rel="nofollow">Recurring Payments</a> created from the Recurring Payment Job.</p>
     * @param recurringPayments values to be set
     */

    @JsonIgnore
    public void setRecurringPayments(final RecurringPaymentReference... recurringPayments);

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPayment" rel="nofollow">Recurring Payments</a> created from the Recurring Payment Job.</p>
     * @param recurringPayments values to be set
     */

    public void setRecurringPayments(final List<RecurringPaymentReference> recurringPayments);

    /**
     *  <p>Status of the Recurring Payment Job.</p>
     * @param status value to be set
     */

    public void setStatus(final RecurringPaymentJobStatus status);

    /**
     *  <p>Date and time (UTC) the Recurring Payment Job was initially created.</p>
     * @param createdAt value to be set
     */

    public void setCreatedAt(final ZonedDateTime createdAt);

    /**
     *  <p>Date and time (UTC) the Recurring Payment Job was last updated.</p>
     * @param lastModifiedAt value to be set
     */

    public void setLastModifiedAt(final ZonedDateTime lastModifiedAt);

    /**
     * factory method
     * @return instance of RecurringPaymentJob
     */
    public static RecurringPaymentJob of() {
        return new RecurringPaymentJobImpl();
    }

    /**
     * factory method to create a shallow copy RecurringPaymentJob
     * @param template instance to be copied
     * @return copy instance
     */
    public static RecurringPaymentJob of(final RecurringPaymentJob template) {
        RecurringPaymentJobImpl instance = new RecurringPaymentJobImpl();
        instance.setId(template.getId());
        instance.setVersion(template.getVersion());
        instance.setKey(template.getKey());
        instance.setOriginPayment(template.getOriginPayment());
        instance.setPaymentMethod(template.getPaymentMethod());
        instance.setRecurringPayments(template.getRecurringPayments());
        instance.setStatus(template.getStatus());
        instance.setCreatedAt(template.getCreatedAt());
        instance.setLastModifiedAt(template.getLastModifiedAt());
        return instance;
    }

    public RecurringPaymentJob copyDeep();

    /**
     * factory method to create a deep copy of RecurringPaymentJob
     * @param template instance to be copied
     * @return copy instance
     */
    @Nullable
    public static RecurringPaymentJob deepCopy(@Nullable final RecurringPaymentJob template) {
        if (template == null) {
            return null;
        }
        RecurringPaymentJobImpl instance = new RecurringPaymentJobImpl();
        instance.setId(template.getId());
        instance.setVersion(template.getVersion());
        instance.setKey(template.getKey());
        instance.setOriginPayment(
            com.commercetools.checkout.models.payment.PaymentReference.deepCopy(template.getOriginPayment()));
        instance.setPaymentMethod(
            com.commercetools.checkout.models.common.PaymentMethodReference.deepCopy(template.getPaymentMethod()));
        instance.setRecurringPayments(Optional.ofNullable(template.getRecurringPayments())
                .map(t -> t.stream()
                        .map(com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference::deepCopy)
                        .collect(Collectors.toList()))
                .orElse(null));
        instance.setStatus(com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatus
                .deepCopy(template.getStatus()));
        instance.setCreatedAt(template.getCreatedAt());
        instance.setLastModifiedAt(template.getLastModifiedAt());
        return instance;
    }

    /**
     * builder factory method for RecurringPaymentJob
     * @return builder
     */
    public static RecurringPaymentJobBuilder builder() {
        return RecurringPaymentJobBuilder.of();
    }

    /**
     * create builder for RecurringPaymentJob instance
     * @param template instance with prefilled values for the builder
     * @return builder
     */
    public static RecurringPaymentJobBuilder builder(final RecurringPaymentJob template) {
        return RecurringPaymentJobBuilder.of(template);
    }

    /**
     * accessor map function
     * @param <T> mapped type
     * @param helper function to map the object
     * @return mapped value
     */
    default <T> T withRecurringPaymentJob(Function<RecurringPaymentJob, T> helper) {
        return helper.apply(this);
    }

    /**
     * gives a TypeReference for usage with Jackson DataBind
     * @return TypeReference
     */
    public static tools.jackson.core.type.TypeReference<RecurringPaymentJob> typeReference() {
        return new tools.jackson.core.type.TypeReference<RecurringPaymentJob>() {
            @Override
            public String toString() {
                return "TypeReference<RecurringPaymentJob>";
            }
        };
    }
}
