
package com.commercetools.checkout.models.recurring_payment_job;

import java.time.*;
import java.util.*;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.vrap.rmf.base.client.ModelBase;
import io.vrap.rmf.base.client.utils.Generated;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import tools.jackson.databind.annotation.*;

/**
 *  <p>Draft type to create a <a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPaymentJob" rel="nofollow">RecurringPaymentJob</a>.</p>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
public class RecurringPaymentJobDraftImpl implements RecurringPaymentJobDraft, ModelBase {

    private String key;

    private com.commercetools.checkout.models.payment.PaymentReference originPayment;

    private com.commercetools.checkout.models.common.PaymentMethodReference paymentMethod;

    /**
     * create instance with all properties
     */
    @JsonCreator
    RecurringPaymentJobDraftImpl(@JsonProperty("key") final String key,
            @JsonProperty("originPayment") final com.commercetools.checkout.models.payment.PaymentReference originPayment,
            @JsonProperty("paymentMethod") final com.commercetools.checkout.models.common.PaymentMethodReference paymentMethod) {
        this.key = key;
        this.originPayment = originPayment;
        this.paymentMethod = paymentMethod;
    }

    /**
     * create empty instance
     */
    public RecurringPaymentJobDraftImpl() {
    }

    /**
     *  <p>User-defined unique identifier of the Recurring Payment Job.</p>
     */

    public String getKey() {
        return this.key;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generates the <span>Recurring Order</span>.</p>
     */

    public com.commercetools.checkout.models.payment.PaymentReference getOriginPayment() {
        return this.originPayment;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     */

    public com.commercetools.checkout.models.common.PaymentMethodReference getPaymentMethod() {
        return this.paymentMethod;
    }

    public void setKey(final String key) {
        this.key = key;
    }

    public void setOriginPayment(final com.commercetools.checkout.models.payment.PaymentReference originPayment) {
        this.originPayment = originPayment;
    }

    public void setPaymentMethod(final com.commercetools.checkout.models.common.PaymentMethodReference paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;

        if (o == null || getClass() != o.getClass())
            return false;

        RecurringPaymentJobDraftImpl that = (RecurringPaymentJobDraftImpl) o;

        return new EqualsBuilder().append(key, that.key)
                .append(originPayment, that.originPayment)
                .append(paymentMethod, that.paymentMethod)
                .append(key, that.key)
                .append(originPayment, that.originPayment)
                .append(paymentMethod, that.paymentMethod)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37).append(key).append(originPayment).append(paymentMethod).toHashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE).append("key", key)
                .append("originPayment", originPayment)
                .append("paymentMethod", paymentMethod)
                .build();
    }

    @Override
    public RecurringPaymentJobDraft copyDeep() {
        return RecurringPaymentJobDraft.deepCopy(this);
    }
}
