
package com.commercetools.checkout.models.recurring_payment_job;

import java.time.*;
import java.util.*;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.vrap.rmf.base.client.ModelBase;
import io.vrap.rmf.base.client.utils.Generated;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import tools.jackson.databind.annotation.*;

/**
 *  <p>Links a <a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made through Checkout to the <a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the resulting <span>Recurring Order</span>.</p>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
public class RecurringPaymentJobImpl implements RecurringPaymentJob, ModelBase {

    private String id;

    private Integer version;

    private String key;

    private com.commercetools.checkout.models.payment.PaymentReference originPayment;

    private com.commercetools.checkout.models.common.PaymentMethodReference paymentMethod;

    private java.util.List<com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference> recurringPayments;

    private com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatus status;

    private java.time.ZonedDateTime createdAt;

    private java.time.ZonedDateTime lastModifiedAt;

    /**
     * create instance with all properties
     */
    @JsonCreator
    RecurringPaymentJobImpl(@JsonProperty("id") final String id, @JsonProperty("version") final Integer version,
            @JsonProperty("key") final String key,
            @JsonProperty("originPayment") final com.commercetools.checkout.models.payment.PaymentReference originPayment,
            @JsonProperty("paymentMethod") final com.commercetools.checkout.models.common.PaymentMethodReference paymentMethod,
            @JsonProperty("recurringPayments") final java.util.List<com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference> recurringPayments,
            @JsonProperty("status") final com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatus status,
            @JsonProperty("createdAt") final java.time.ZonedDateTime createdAt,
            @JsonProperty("lastModifiedAt") final java.time.ZonedDateTime lastModifiedAt) {
        this.id = id;
        this.version = version;
        this.key = key;
        this.originPayment = originPayment;
        this.paymentMethod = paymentMethod;
        this.recurringPayments = recurringPayments;
        this.status = status;
        this.createdAt = createdAt;
        this.lastModifiedAt = lastModifiedAt;
    }

    /**
     * create empty instance
     */
    public RecurringPaymentJobImpl() {
    }

    /**
     *  <p>Unique identifier of the Recurring Payment Job.</p>
     */

    public String getId() {
        return this.id;
    }

    /**
     *  <p>Current version of the Recurring Payment Job.</p>
     */

    public Integer getVersion() {
        return this.version;
    }

    /**
     *  <p>User-defined unique identifier of the Recurring Payment Job.</p>
     */

    public String getKey() {
        return this.key;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generated the <span>Recurring Order</span>.</p>
     */

    public com.commercetools.checkout.models.payment.PaymentReference getOriginPayment() {
        return this.originPayment;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     */

    public com.commercetools.checkout.models.common.PaymentMethodReference getPaymentMethod() {
        return this.paymentMethod;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPayment" rel="nofollow">Recurring Payments</a> created from the Recurring Payment Job.</p>
     */

    public java.util.List<com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference> getRecurringPayments() {
        return this.recurringPayments;
    }

    /**
     *  <p>Status of the Recurring Payment Job.</p>
     */

    public com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatus getStatus() {
        return this.status;
    }

    /**
     *  <p>Date and time (UTC) the Recurring Payment Job was initially created.</p>
     */

    public java.time.ZonedDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     *  <p>Date and time (UTC) the Recurring Payment Job was last updated.</p>
     */

    public java.time.ZonedDateTime getLastModifiedAt() {
        return this.lastModifiedAt;
    }

    public void setId(final String id) {
        this.id = id;
    }

    public void setVersion(final Integer version) {
        this.version = version;
    }

    public void setKey(final String key) {
        this.key = key;
    }

    public void setOriginPayment(final com.commercetools.checkout.models.payment.PaymentReference originPayment) {
        this.originPayment = originPayment;
    }

    public void setPaymentMethod(final com.commercetools.checkout.models.common.PaymentMethodReference paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public void setRecurringPayments(
            final com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference... recurringPayments) {
        this.recurringPayments = new ArrayList<>(Arrays.asList(recurringPayments));
    }

    public void setRecurringPayments(
            final java.util.List<com.commercetools.checkout.models.recurring_payment.RecurringPaymentReference> recurringPayments) {
        this.recurringPayments = recurringPayments;
    }

    public void setStatus(
            final com.commercetools.checkout.models.recurring_payment_job.RecurringPaymentJobStatus status) {
        this.status = status;
    }

    public void setCreatedAt(final java.time.ZonedDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setLastModifiedAt(final java.time.ZonedDateTime lastModifiedAt) {
        this.lastModifiedAt = lastModifiedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;

        if (o == null || getClass() != o.getClass())
            return false;

        RecurringPaymentJobImpl that = (RecurringPaymentJobImpl) o;

        return new EqualsBuilder().append(id, that.id)
                .append(version, that.version)
                .append(key, that.key)
                .append(originPayment, that.originPayment)
                .append(paymentMethod, that.paymentMethod)
                .append(recurringPayments, that.recurringPayments)
                .append(status, that.status)
                .append(createdAt, that.createdAt)
                .append(lastModifiedAt, that.lastModifiedAt)
                .append(id, that.id)
                .append(version, that.version)
                .append(key, that.key)
                .append(originPayment, that.originPayment)
                .append(paymentMethod, that.paymentMethod)
                .append(recurringPayments, that.recurringPayments)
                .append(status, that.status)
                .append(createdAt, that.createdAt)
                .append(lastModifiedAt, that.lastModifiedAt)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37).append(id)
                .append(version)
                .append(key)
                .append(originPayment)
                .append(paymentMethod)
                .append(recurringPayments)
                .append(status)
                .append(createdAt)
                .append(lastModifiedAt)
                .toHashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE).append("id", id)
                .append("version", version)
                .append("key", key)
                .append("originPayment", originPayment)
                .append("paymentMethod", paymentMethod)
                .append("recurringPayments", recurringPayments)
                .append("status", status)
                .append("createdAt", createdAt)
                .append("lastModifiedAt", lastModifiedAt)
                .build();
    }

    @Override
    public RecurringPaymentJob copyDeep() {
        return RecurringPaymentJob.deepCopy(this);
    }
}
