
package com.commercetools.checkout.models.recurring_payment_job;

import java.util.Arrays;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import io.vrap.rmf.base.client.JsonEnum;
import io.vrap.rmf.base.client.utils.Generated;

/**
 *  <p>The state of the <a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPaymentJob" rel="nofollow">RecurringPaymentJob</a>.</p>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
public interface RecurringPaymentJobState extends JsonEnum {

    /**
    <p>The Recurring Payment Job has been created and is waiting to be processed.</p> */
    RecurringPaymentJobState INITIAL = RecurringPaymentJobStateEnum.INITIAL;
    /**
    <p>Checkout is setting up the future payment method and <span>Connector</span> for the Orders generated by the Recurring Order.</p> */
    RecurringPaymentJobState PENDING = RecurringPaymentJobStateEnum.PENDING;
    /**
    <p>The Recurring Payment Job completed successfully. Checkout created the <a href="https://docs.commercetools.com/apis/ctp:checkout:type:RecurringPayment" rel="nofollow">Recurring Payment</a> needed to process the future payments of the Recurring Order.</p> */
    RecurringPaymentJobState COMPLETED = RecurringPaymentJobStateEnum.COMPLETED;
    /**
    <p>The Recurring Payment Job failed.</p> */
    RecurringPaymentJobState FAILED = RecurringPaymentJobStateEnum.FAILED;

    /**
     * possible values of RecurringPaymentJobState
     */
    enum RecurringPaymentJobStateEnum implements RecurringPaymentJobState {
        /**
         * Initial
         */
        INITIAL("Initial"),

        /**
         * Pending
         */
        PENDING("Pending"),

        /**
         * Completed
         */
        COMPLETED("Completed"),

        /**
         * Failed
         */
        FAILED("Failed");
        private final String jsonName;

        private RecurringPaymentJobStateEnum(final String jsonName) {
            this.jsonName = jsonName;
        }

        public String getJsonName() {
            return jsonName;
        }

        public String toString() {
            return jsonName;
        }
    }

    /**
     * the JSON value
     * @return json value
     */
    @JsonValue
    String getJsonName();

    /**
     * the enum value
     * @return name
     */
    String name();

    /**
     * convert value to string
     * @return string representation
     */
    String toString();

    /**
     * factory method for a enum value of RecurringPaymentJobState
     * if no enum has been found an anonymous instance will be created
     * @param value the enum value to be wrapped
     * @return enum instance
     */
    @JsonCreator
    public static RecurringPaymentJobState findEnum(String value) {
        return findEnumViaJsonName(value).orElse(new RecurringPaymentJobState() {
            @Override
            public String getJsonName() {
                return value;
            }

            @Override
            public String name() {
                return value.toUpperCase();
            }

            public String toString() {
                return value;
            }
        });
    }

    /**
     * method to find enum using the JSON value
     * @param jsonName the json value to be wrapped
     * @return optional of enum instance
     */
    public static Optional<RecurringPaymentJobState> findEnumViaJsonName(String jsonName) {
        return Arrays.stream(values()).filter(t -> t.getJsonName().equals(jsonName)).findFirst();
    }

    /**
     * possible enum values
     * @return array of possible enum values
     */
    public static RecurringPaymentJobState[] values() {
        return RecurringPaymentJobStateEnum.values();
    }

}
