
package com.commercetools.checkout.models.recurring_payment_job;

import java.util.*;
import java.util.function.Function;

import javax.annotation.Nullable;

import io.vrap.rmf.base.client.Builder;
import io.vrap.rmf.base.client.utils.Generated;

/**
 * RecurringPaymentJobDraftBuilder
 * <hr>
 * Example to create an instance using the builder pattern
 * <div class=code-example>
 * <pre><code class='java'>
 *     RecurringPaymentJobDraft recurringPaymentJobDraft = RecurringPaymentJobDraft.builder()
 *             .originPayment(originPaymentBuilder -> originPaymentBuilder)
 *             .paymentMethod(paymentMethodBuilder -> paymentMethodBuilder)
 *             .build()
 * </code></pre>
 * </div>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
public class RecurringPaymentJobDraftBuilder implements Builder<RecurringPaymentJobDraft> {

    @Nullable
    private String key;

    private com.commercetools.checkout.models.payment.PaymentReference originPayment;

    private com.commercetools.checkout.models.common.PaymentMethodReference paymentMethod;

    /**
     *  <p>User-defined unique identifier of the Recurring Payment Job.</p>
     * @param key value to be set
     * @return Builder
     */

    public RecurringPaymentJobDraftBuilder key(@Nullable final String key) {
        this.key = key;
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generates the <span>Recurring Order</span>.</p>
     * @param builder function to build the originPayment value
     * @return Builder
     */

    public RecurringPaymentJobDraftBuilder originPayment(
            Function<com.commercetools.checkout.models.payment.PaymentReferenceBuilder, com.commercetools.checkout.models.payment.PaymentReferenceBuilder> builder) {
        this.originPayment = builder.apply(com.commercetools.checkout.models.payment.PaymentReferenceBuilder.of())
                .build();
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generates the <span>Recurring Order</span>.</p>
     * @param builder function to build the originPayment value
     * @return Builder
     */

    public RecurringPaymentJobDraftBuilder withOriginPayment(
            Function<com.commercetools.checkout.models.payment.PaymentReferenceBuilder, com.commercetools.checkout.models.payment.PaymentReference> builder) {
        this.originPayment = builder.apply(com.commercetools.checkout.models.payment.PaymentReferenceBuilder.of());
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generates the <span>Recurring Order</span>.</p>
     * @param originPayment value to be set
     * @return Builder
     */

    public RecurringPaymentJobDraftBuilder originPayment(
            final com.commercetools.checkout.models.payment.PaymentReference originPayment) {
        this.originPayment = originPayment;
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     * @param builder function to build the paymentMethod value
     * @return Builder
     */

    public RecurringPaymentJobDraftBuilder paymentMethod(
            Function<com.commercetools.checkout.models.common.PaymentMethodReferenceBuilder, com.commercetools.checkout.models.common.PaymentMethodReferenceBuilder> builder) {
        this.paymentMethod = builder.apply(com.commercetools.checkout.models.common.PaymentMethodReferenceBuilder.of())
                .build();
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     * @param builder function to build the paymentMethod value
     * @return Builder
     */

    public RecurringPaymentJobDraftBuilder withPaymentMethod(
            Function<com.commercetools.checkout.models.common.PaymentMethodReferenceBuilder, com.commercetools.checkout.models.common.PaymentMethodReference> builder) {
        this.paymentMethod = builder.apply(com.commercetools.checkout.models.common.PaymentMethodReferenceBuilder.of());
        return this;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     * @param paymentMethod value to be set
     * @return Builder
     */

    public RecurringPaymentJobDraftBuilder paymentMethod(
            final com.commercetools.checkout.models.common.PaymentMethodReference paymentMethod) {
        this.paymentMethod = paymentMethod;
        return this;
    }

    /**
     *  <p>User-defined unique identifier of the Recurring Payment Job.</p>
     * @return key
     */

    @Nullable
    public String getKey() {
        return this.key;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:Payment" rel="nofollow">Payment</a> made for the Cart that generates the <span>Recurring Order</span>.</p>
     * @return originPayment
     */

    public com.commercetools.checkout.models.payment.PaymentReference getOriginPayment() {
        return this.originPayment;
    }

    /**
     *  <p><a href="https://docs.commercetools.com/apis/ctp:api:type:PaymentMethod" rel="nofollow">PaymentMethod</a> that must be used to pay the Orders generated by the Recurring Order.</p>
     * @return paymentMethod
     */

    public com.commercetools.checkout.models.common.PaymentMethodReference getPaymentMethod() {
        return this.paymentMethod;
    }

    /**
     * builds RecurringPaymentJobDraft with checking for non-null required values
     * @return RecurringPaymentJobDraft
     */
    public RecurringPaymentJobDraft build() {
        Objects.requireNonNull(originPayment, RecurringPaymentJobDraft.class + ": originPayment is missing");
        Objects.requireNonNull(paymentMethod, RecurringPaymentJobDraft.class + ": paymentMethod is missing");
        return new RecurringPaymentJobDraftImpl(key, originPayment, paymentMethod);
    }

    /**
     * builds RecurringPaymentJobDraft without checking for non-null required values
     * @return RecurringPaymentJobDraft
     */
    public RecurringPaymentJobDraft buildUnchecked() {
        return new RecurringPaymentJobDraftImpl(key, originPayment, paymentMethod);
    }

    /**
     * factory method for an instance of RecurringPaymentJobDraftBuilder
     * @return builder
     */
    public static RecurringPaymentJobDraftBuilder of() {
        return new RecurringPaymentJobDraftBuilder();
    }

    /**
     * create builder for RecurringPaymentJobDraft instance
     * @param template instance with prefilled values for the builder
     * @return builder
     */
    public static RecurringPaymentJobDraftBuilder of(final RecurringPaymentJobDraft template) {
        RecurringPaymentJobDraftBuilder builder = new RecurringPaymentJobDraftBuilder();
        builder.key = template.getKey();
        builder.originPayment = template.getOriginPayment();
        builder.paymentMethod = template.getPaymentMethod();
        return builder;
    }

}
