on:
    - workflow_dispatch

name: Benchmark

# Declare default permissions as read only.
permissions: { }

jobs:
    benchmark:
        name: Benchmark

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            - uses: gradle/actions/wrapper-validation@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1

            - name: Setup Java
              uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Run benchmark
              run: ./gradlew clean benchmark
              env:
                  CTP_CLIENT_ID: ${{ secrets.CTP_CLIENT_ID_PR }}
                  CTP_CLIENT_SECRET: ${{ secrets.CTP_CLIENT_SECRET_PR }}
                  CTP_PROJECT_KEY: ${{ secrets.CTP_PROJECT_KEY_PR }}
                  CTP_JVM_SDK_LOG_LEVEL: OFF
