on:
    - workflow_dispatch

name: Benchmark

# Declare default permissions as read only.
permissions: { }

jobs:
    benchmark:
        name: Benchmark

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

            - uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

            - name: Setup Java
              uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Run benchmark
              run: ./gradlew clean benchmark
              env:
                  CTP_CLIENT_ID: ${{ secrets.CTP_CLIENT_ID_PR }}
                  CTP_CLIENT_SECRET: ${{ secrets.CTP_CLIENT_SECRET_PR }}
                  CTP_PROJECT_KEY: ${{ secrets.CTP_PROJECT_KEY_PR }}
                  CTP_JVM_SDK_LOG_LEVEL: OFF
