on:
    - workflow_dispatch

name: Benchmark

# Declare default permissions as read only.
permissions: { }

jobs:
    benchmark:
        name: Benchmark

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

            - uses: gradle/wrapper-validation-action@216d1ad2b3710bf005dc39237337b9673fd8fcd5 # v3.3.2

            - name: Setup Java
              uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Run benchmark
              run: ./gradlew clean benchmark
              env:
                  CTP_CLIENT_ID: ${{ secrets.CTP_CLIENT_ID_PR }}
                  CTP_CLIENT_SECRET: ${{ secrets.CTP_CLIENT_SECRET_PR }}
                  CTP_PROJECT_KEY: ${{ secrets.CTP_PROJECT_KEY_PR }}
                  CTP_JVM_SDK_LOG_LEVEL: OFF
