on:
  push:
    branches:
      - 'gen-sdk-updates'

name: Create Changes PR

# Declare default permissions as read only.
permissions: read-all

jobs:
  create_pr:
    name: Create/Update PR

    runs-on: ubuntu-latest
    steps:
        # Get GitHub token via the CT SDKs App
      - name: Generate GitHub token (via CT SDKs App)
        id: generate_github_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SDK_APP_ID }}
          private-key: ${{ secrets.SDK_APP_PEM }}

      - name: Get App user
        id: get_app_user
        env:
           GITHUB_TOKEN: ${{ steps.generate_github_token.outputs.token }}
        run: |
          export GH_APP_USER=`gh api /users/ct-sdks%5Bbot%5D | jq .id`
          echo "email=${GH_APP_USER}+ct-sdks[bot]@users.noreply.github.com" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_github_token.outputs.token }}

      - uses: gradle/wrapper-validation-action@342dbebe7272035434f9baccc29a816ec6dd2c7b

      - uses: jenschude/auto-create-pr-action@8733ffe7f93fbeab30113ed3964dfb02bb6984b5
        with:
            request_title: "Update generated SDKs"
            github_token: ${{ steps.generate_github_token.outputs.token }}
            request_body: |
                - [ ] Changeset added

                ### Features

                ### Fixes

                ### Breaking changes
