on:
  push:
    branches:
      - 'gen-sdk-updates'

name: Create Changes PR

# Declare default permissions as read only.
permissions: read-all

jobs:
  create_pr:
    name: Create/Update PR

    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@342dbebe7272035434f9baccc29a816ec6dd2c7b

      - uses: jenschude/auto-create-pr-action@8733ffe7f93fbeab30113ed3964dfb02bb6984b5
        with:
            request_title: "Update generated SDKs"
            github_token: ${{ secrets.GITHUB_TOKEN }}
            request_body: |
                - [ ] Changeset added

                ### Features

                ### Fixes

                ### Breaking changes
