on:
  push:
    branches:
      - 'gen-sdk-updates'

name: Create Changes PR

# Declare default permissions as read only.
permissions: read-all

jobs:
  create_pr:
    name: Create/Update PR

    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: jenschude/auto-create-pr-action@v0.3.1
        with:
            request_title: "Update generated SDKs"
            github_token: ${{ secrets.GITHUB_TOKEN }}
            request_body: |
                - [ ] Changeset added

                ### Features

                ### Fixes

                ### Breaking changes
