on:
  push:
    branches:
      - 'gen-sdk-updates'
      - 'after-release'

name: Create Changes PR

# Declare default permissions as read only.
permissions: read-all

jobs:
  create_pr:
    name: Create/Update PR

    runs-on: ubuntu-latest
    steps:
        # Get GitHub token via the CT SDKs App
      - name: Generate GitHub token (via CT SDKs App)
        id: generate_github_token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        with:
          app-id: ${{ secrets.CT_SDKS_APP_ID }}
          private-key: ${{ secrets.CT_SDKS_APP_PEM }}

      - name: Get App user
        id: get_app_user
        env:
           GITHUB_TOKEN: ${{ steps.generate_github_token.outputs.token }}
        run: |
          export GH_APP_USER=`gh api /users/ct-sdks%5Bbot%5D | jq .id`
          echo "email=${GH_APP_USER}+ct-sdks[bot]@users.noreply.github.com" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ steps.generate_github_token.outputs.token }}

      - uses: gradle/actions/wrapper-validation@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4

      - uses: jenschude/auto-create-pr-action@a5369414c74963e6ec065dab49066d3711b8c1db # v0.3.2
        if: github.ref_name == 'gen-sdk-updates'
        with:
            request_title: "Update generated SDKs"
            github_token: ${{ steps.generate_github_token.outputs.token }}
            label: automerge
            request_body: |
                - [ ] Changeset added

                ### Features

                ### Fixes

                ### Breaking changes

      - uses: jenschude/auto-create-pr-action@a5369414c74963e6ec065dab49066d3711b8c1db # v0.3.2
        if: github.ref_name == 'after-release'
        with:
            request_title: "Update changelog"
            github_token: ${{ steps.generate_github_token.outputs.token }}
            label: automerge
            request_body: |
                Changelog updates
