on:
  push:
    branches:
      - 'gen-sdk-updates'

name: Create Changes PR

# Declare default permissions as read only.
permissions: read-all

jobs:
  create_pr:
    name: Create/Update PR

    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4

      - uses: jenschude/auto-create-pr-action@v8733ffe7f93fbeab30113ed3964dfb02bb6984b5
        with:
            request_title: "Update generated SDKs"
            github_token: ${{ secrets.GITHUB_TOKEN }}
            request_body: |
                - [ ] Changeset added

                ### Features

                ### Fixes

                ### Breaking changes
