on:
  - workflow_dispatch

name: Release snapshot

# Declare default permissions as read only.
permissions: read-all

jobs:
  release:
    name: Build and release

    runs-on: ubuntu-latest

    steps:
      # Get GitHub token via the CT SDKs App
      - name: Generate GitHub token (via CT SDKs App)
        id: generate_github_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ secrets.CT_SDKS_APP_ID }}
          private-key: ${{ secrets.CT_SDKS_APP_PEM }}

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
            token: ${{ steps.generate_github_token.outputs.token }}

      - uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Setup Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@b1de5da23ed0a6d14e0aeee8ed52fdd87af2363c # v2.0.2

      - run: scripts/setup-signing-key.sh
        env:
          DECRYPTER: ${{ secrets.DECRYPTER }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Build and Test
        run: ./gradlew --build-cache clean test

      - name: Release
        run: ./gradlew --build-cache publishToSonatype
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - run: rm -rf ~/.gradle/gradle.properties
