
package com.commercetools.api.models.cart;

import java.util.*;
import java.util.function.Function;

import javax.annotation.Nullable;

import io.vrap.rmf.base.client.Builder;
import io.vrap.rmf.base.client.utils.Generated;

/**
 * CartSetRecurringPaymentConfigurationActionBuilder
 * <hr>
 * Example to create an instance using the builder pattern
 * <div class=code-example>
 * <pre><code class='java'>
 *     CartSetRecurringPaymentConfigurationAction cartSetRecurringPaymentConfigurationAction = CartSetRecurringPaymentConfigurationAction.builder()
 *             .build()
 * </code></pre>
 * </div>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
public class CartSetRecurringPaymentConfigurationActionBuilder
        implements Builder<CartSetRecurringPaymentConfigurationAction> {

    @Nullable
    private com.commercetools.api.models.cart.RecurringPaymentConfigurationDraft recurringPaymentConfiguration;

    /**
     *  <p>Value to set. If omitted, any existing value is removed and the Orders generated by the <a href="https://docs.commercetools.com/apis/ctp:api:type:RecurringOrder" rel="nofollow">RecurringOrder</a> are created without collecting payment first.</p>
     * @param builder function to build the recurringPaymentConfiguration value
     * @return Builder
     */

    public CartSetRecurringPaymentConfigurationActionBuilder recurringPaymentConfiguration(
            Function<com.commercetools.api.models.cart.RecurringPaymentConfigurationDraftBuilder, com.commercetools.api.models.cart.RecurringPaymentConfigurationDraftBuilder> builder) {
        this.recurringPaymentConfiguration = builder
                .apply(com.commercetools.api.models.cart.RecurringPaymentConfigurationDraftBuilder.of())
                .build();
        return this;
    }

    /**
     *  <p>Value to set. If omitted, any existing value is removed and the Orders generated by the <a href="https://docs.commercetools.com/apis/ctp:api:type:RecurringOrder" rel="nofollow">RecurringOrder</a> are created without collecting payment first.</p>
     * @param builder function to build the recurringPaymentConfiguration value
     * @return Builder
     */

    public CartSetRecurringPaymentConfigurationActionBuilder withRecurringPaymentConfiguration(
            Function<com.commercetools.api.models.cart.RecurringPaymentConfigurationDraftBuilder, com.commercetools.api.models.cart.RecurringPaymentConfigurationDraft> builder) {
        this.recurringPaymentConfiguration = builder
                .apply(com.commercetools.api.models.cart.RecurringPaymentConfigurationDraftBuilder.of());
        return this;
    }

    /**
     *  <p>Value to set. If omitted, any existing value is removed and the Orders generated by the <a href="https://docs.commercetools.com/apis/ctp:api:type:RecurringOrder" rel="nofollow">RecurringOrder</a> are created without collecting payment first.</p>
     * @param recurringPaymentConfiguration value to be set
     * @return Builder
     */

    public CartSetRecurringPaymentConfigurationActionBuilder recurringPaymentConfiguration(
            @Nullable final com.commercetools.api.models.cart.RecurringPaymentConfigurationDraft recurringPaymentConfiguration) {
        this.recurringPaymentConfiguration = recurringPaymentConfiguration;
        return this;
    }

    /**
     *  <p>Value to set. If omitted, any existing value is removed and the Orders generated by the <a href="https://docs.commercetools.com/apis/ctp:api:type:RecurringOrder" rel="nofollow">RecurringOrder</a> are created without collecting payment first.</p>
     * @return recurringPaymentConfiguration
     */

    @Nullable
    public com.commercetools.api.models.cart.RecurringPaymentConfigurationDraft getRecurringPaymentConfiguration() {
        return this.recurringPaymentConfiguration;
    }

    /**
     * builds CartSetRecurringPaymentConfigurationAction with checking for non-null required values
     * @return CartSetRecurringPaymentConfigurationAction
     */
    public CartSetRecurringPaymentConfigurationAction build() {
        return new CartSetRecurringPaymentConfigurationActionImpl(recurringPaymentConfiguration);
    }

    /**
     * builds CartSetRecurringPaymentConfigurationAction without checking for non-null required values
     * @return CartSetRecurringPaymentConfigurationAction
     */
    public CartSetRecurringPaymentConfigurationAction buildUnchecked() {
        return new CartSetRecurringPaymentConfigurationActionImpl(recurringPaymentConfiguration);
    }

    /**
     * factory method for an instance of CartSetRecurringPaymentConfigurationActionBuilder
     * @return builder
     */
    public static CartSetRecurringPaymentConfigurationActionBuilder of() {
        return new CartSetRecurringPaymentConfigurationActionBuilder();
    }

    /**
     * create builder for CartSetRecurringPaymentConfigurationAction instance
     * @param template instance with prefilled values for the builder
     * @return builder
     */
    public static CartSetRecurringPaymentConfigurationActionBuilder of(
            final CartSetRecurringPaymentConfigurationAction template) {
        CartSetRecurringPaymentConfigurationActionBuilder builder = new CartSetRecurringPaymentConfigurationActionBuilder();
        builder.recurringPaymentConfiguration = template.getRecurringPaymentConfiguration();
        return builder;
    }

}
