
package com.commercetools.api.models.cart;

import java.time.*;
import java.util.*;
import java.util.function.Function;

import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.*;

import io.vrap.rmf.base.client.utils.Generated;

import jakarta.validation.Valid;
import tools.jackson.databind.annotation.*;

/**
 *  <p>Sets the <code>paymentStrategy</code> and the <code>paymentAllocations</code> of the <a href="https://docs.commercetools.com/apis/ctp:api:type:RecurringPaymentConfiguration" rel="nofollow">RecurringPaymentConfiguration</a> together, replacing any existing configuration.</p>
 *
 * <hr>
 * Example to create an instance using the builder pattern
 * <div class=code-example>
 * <pre><code class='java'>
 *     CartSetRecurringPaymentConfigurationAction cartSetRecurringPaymentConfigurationAction = CartSetRecurringPaymentConfigurationAction.builder()
 *             .build()
 * </code></pre>
 * </div>
 */
@io.vrap.rmf.base.client.utils.json.SubType("setRecurringPaymentConfiguration")
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
@JsonDeserialize(as = CartSetRecurringPaymentConfigurationActionImpl.class)
public interface CartSetRecurringPaymentConfigurationAction extends CartUpdateAction {

    /**
     * discriminator value for CartSetRecurringPaymentConfigurationAction
     */
    String SET_RECURRING_PAYMENT_CONFIGURATION = "setRecurringPaymentConfiguration";

    /**
     *  <p>Value to set. If omitted, any existing value is removed and the Orders generated by the <a href="https://docs.commercetools.com/apis/ctp:api:type:RecurringOrder" rel="nofollow">RecurringOrder</a> are created without collecting payment first.</p>
     * @return recurringPaymentConfiguration
     */
    @Valid
    @JsonProperty("recurringPaymentConfiguration")
    public RecurringPaymentConfigurationDraft getRecurringPaymentConfiguration();

    /**
     *  <p>Value to set. If omitted, any existing value is removed and the Orders generated by the <a href="https://docs.commercetools.com/apis/ctp:api:type:RecurringOrder" rel="nofollow">RecurringOrder</a> are created without collecting payment first.</p>
     * @param recurringPaymentConfiguration value to be set
     */

    public void setRecurringPaymentConfiguration(
            final RecurringPaymentConfigurationDraft recurringPaymentConfiguration);

    /**
     * factory method
     * @return instance of CartSetRecurringPaymentConfigurationAction
     */
    public static CartSetRecurringPaymentConfigurationAction of() {
        return new CartSetRecurringPaymentConfigurationActionImpl();
    }

    /**
     * factory method to create a shallow copy CartSetRecurringPaymentConfigurationAction
     * @param template instance to be copied
     * @return copy instance
     */
    public static CartSetRecurringPaymentConfigurationAction of(
            final CartSetRecurringPaymentConfigurationAction template) {
        CartSetRecurringPaymentConfigurationActionImpl instance = new CartSetRecurringPaymentConfigurationActionImpl();
        instance.setRecurringPaymentConfiguration(template.getRecurringPaymentConfiguration());
        return instance;
    }

    public CartSetRecurringPaymentConfigurationAction copyDeep();

    /**
     * factory method to create a deep copy of CartSetRecurringPaymentConfigurationAction
     * @param template instance to be copied
     * @return copy instance
     */
    @Nullable
    public static CartSetRecurringPaymentConfigurationAction deepCopy(
            @Nullable final CartSetRecurringPaymentConfigurationAction template) {
        if (template == null) {
            return null;
        }
        CartSetRecurringPaymentConfigurationActionImpl instance = new CartSetRecurringPaymentConfigurationActionImpl();
        instance.setRecurringPaymentConfiguration(com.commercetools.api.models.cart.RecurringPaymentConfigurationDraft
                .deepCopy(template.getRecurringPaymentConfiguration()));
        return instance;
    }

    /**
     * builder factory method for CartSetRecurringPaymentConfigurationAction
     * @return builder
     */
    public static CartSetRecurringPaymentConfigurationActionBuilder builder() {
        return CartSetRecurringPaymentConfigurationActionBuilder.of();
    }

    /**
     * create builder for CartSetRecurringPaymentConfigurationAction instance
     * @param template instance with prefilled values for the builder
     * @return builder
     */
    public static CartSetRecurringPaymentConfigurationActionBuilder builder(
            final CartSetRecurringPaymentConfigurationAction template) {
        return CartSetRecurringPaymentConfigurationActionBuilder.of(template);
    }

    /**
     * accessor map function
     * @param <T> mapped type
     * @param helper function to map the object
     * @return mapped value
     */
    default <T> T withCartSetRecurringPaymentConfigurationAction(
            Function<CartSetRecurringPaymentConfigurationAction, T> helper) {
        return helper.apply(this);
    }

    /**
     * gives a TypeReference for usage with Jackson DataBind
     * @return TypeReference
     */
    public static tools.jackson.core.type.TypeReference<CartSetRecurringPaymentConfigurationAction> typeReference() {
        return new tools.jackson.core.type.TypeReference<CartSetRecurringPaymentConfigurationAction>() {
            @Override
            public String toString() {
                return "TypeReference<CartSetRecurringPaymentConfigurationAction>";
            }
        };
    }
}
