
package com.commercetools.api.models.cart;

import java.time.*;
import java.util.*;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.vrap.rmf.base.client.ModelBase;
import io.vrap.rmf.base.client.utils.Generated;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import tools.jackson.databind.annotation.*;

/**
 *  <p>Sets the <code>paymentStrategy</code> and the <code>paymentAllocations</code> of the <a href="https://docs.commercetools.com/apis/ctp:api:type:RecurringPaymentConfiguration" rel="nofollow">RecurringPaymentConfiguration</a> together, replacing any existing configuration.</p>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
public class CartSetRecurringPaymentConfigurationActionImpl
        implements CartSetRecurringPaymentConfigurationAction, ModelBase {

    private String action;

    private com.commercetools.api.models.cart.RecurringPaymentConfigurationDraft recurringPaymentConfiguration;

    /**
     * create instance with all properties
     */
    @JsonCreator
    CartSetRecurringPaymentConfigurationActionImpl(
            @JsonProperty("recurringPaymentConfiguration") final com.commercetools.api.models.cart.RecurringPaymentConfigurationDraft recurringPaymentConfiguration) {
        this.recurringPaymentConfiguration = recurringPaymentConfiguration;
        this.action = SET_RECURRING_PAYMENT_CONFIGURATION;
    }

    /**
     * create empty instance
     */
    public CartSetRecurringPaymentConfigurationActionImpl() {
        this.action = SET_RECURRING_PAYMENT_CONFIGURATION;
    }

    /**
     *
     */

    public String getAction() {
        return this.action;
    }

    /**
     *  <p>Value to set. If omitted, any existing value is removed and the Orders generated by the <a href="https://docs.commercetools.com/apis/ctp:api:type:RecurringOrder" rel="nofollow">RecurringOrder</a> are created without collecting payment first.</p>
     */

    public com.commercetools.api.models.cart.RecurringPaymentConfigurationDraft getRecurringPaymentConfiguration() {
        return this.recurringPaymentConfiguration;
    }

    public void setRecurringPaymentConfiguration(
            final com.commercetools.api.models.cart.RecurringPaymentConfigurationDraft recurringPaymentConfiguration) {
        this.recurringPaymentConfiguration = recurringPaymentConfiguration;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;

        if (o == null || getClass() != o.getClass())
            return false;

        CartSetRecurringPaymentConfigurationActionImpl that = (CartSetRecurringPaymentConfigurationActionImpl) o;

        return new EqualsBuilder().append(action, that.action)
                .append(recurringPaymentConfiguration, that.recurringPaymentConfiguration)
                .append(action, that.action)
                .append(recurringPaymentConfiguration, that.recurringPaymentConfiguration)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37).append(action).append(recurringPaymentConfiguration).toHashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE).append("action", action)
                .append("recurringPaymentConfiguration", recurringPaymentConfiguration)
                .build();
    }

    @Override
    public CartSetRecurringPaymentConfigurationAction copyDeep() {
        return CartSetRecurringPaymentConfigurationAction.deepCopy(this);
    }
}
