
package com.commercetools.api.models.cart;

import java.util.*;
import java.util.function.Function;

import io.vrap.rmf.base.client.Builder;
import io.vrap.rmf.base.client.utils.Generated;

/**
 * RecurringPaymentConfigurationDraftBuilder
 * <hr>
 * Example to create an instance using the builder pattern
 * <div class=code-example>
 * <pre><code class='java'>
 *     RecurringPaymentConfigurationDraft recurringPaymentConfigurationDraft = RecurringPaymentConfigurationDraft.builder()
 *             .paymentStrategy(PaymentStrategy.CHECKOUT)
 *             .plusPaymentAllocations(paymentAllocationsBuilder -> paymentAllocationsBuilder)
 *             .build()
 * </code></pre>
 * </div>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
public class RecurringPaymentConfigurationDraftBuilder implements Builder<RecurringPaymentConfigurationDraft> {

    private com.commercetools.api.models.cart.PaymentStrategy paymentStrategy;

    private java.util.List<com.commercetools.api.models.cart.PaymentAllocationDraft> paymentAllocations;

    /**
     *  <p>Determines how payment is collected for the Orders generated by the Recurring Order.</p>
     * @param paymentStrategy value to be set
     * @return Builder
     */

    public RecurringPaymentConfigurationDraftBuilder paymentStrategy(
            final com.commercetools.api.models.cart.PaymentStrategy paymentStrategy) {
        this.paymentStrategy = paymentStrategy;
        return this;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     * @param paymentAllocations value to be set
     * @return Builder
     */

    public RecurringPaymentConfigurationDraftBuilder paymentAllocations(
            final com.commercetools.api.models.cart.PaymentAllocationDraft... paymentAllocations) {
        this.paymentAllocations = new ArrayList<>(Arrays.asList(paymentAllocations));
        return this;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     * @param paymentAllocations value to be set
     * @return Builder
     */

    public RecurringPaymentConfigurationDraftBuilder paymentAllocations(
            final java.util.List<com.commercetools.api.models.cart.PaymentAllocationDraft> paymentAllocations) {
        this.paymentAllocations = paymentAllocations;
        return this;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     * @param paymentAllocations value to be set
     * @return Builder
     */

    public RecurringPaymentConfigurationDraftBuilder plusPaymentAllocations(
            final com.commercetools.api.models.cart.PaymentAllocationDraft... paymentAllocations) {
        if (this.paymentAllocations == null) {
            this.paymentAllocations = new ArrayList<>();
        }
        this.paymentAllocations.addAll(Arrays.asList(paymentAllocations));
        return this;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     * @param builder function to build the paymentAllocations value
     * @return Builder
     */

    public RecurringPaymentConfigurationDraftBuilder plusPaymentAllocations(
            Function<com.commercetools.api.models.cart.PaymentAllocationDraftBuilder, com.commercetools.api.models.cart.PaymentAllocationDraftBuilder> builder) {
        if (this.paymentAllocations == null) {
            this.paymentAllocations = new ArrayList<>();
        }
        this.paymentAllocations
                .add(builder.apply(com.commercetools.api.models.cart.PaymentAllocationDraftBuilder.of()).build());
        return this;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     * @param builder function to build the paymentAllocations value
     * @return Builder
     */

    public RecurringPaymentConfigurationDraftBuilder withPaymentAllocations(
            Function<com.commercetools.api.models.cart.PaymentAllocationDraftBuilder, com.commercetools.api.models.cart.PaymentAllocationDraftBuilder> builder) {
        this.paymentAllocations = new ArrayList<>();
        this.paymentAllocations
                .add(builder.apply(com.commercetools.api.models.cart.PaymentAllocationDraftBuilder.of()).build());
        return this;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     * @param builder function to build the paymentAllocations value
     * @return Builder
     */

    public RecurringPaymentConfigurationDraftBuilder addPaymentAllocations(
            Function<com.commercetools.api.models.cart.PaymentAllocationDraftBuilder, com.commercetools.api.models.cart.PaymentAllocationDraft> builder) {
        return plusPaymentAllocations(
            builder.apply(com.commercetools.api.models.cart.PaymentAllocationDraftBuilder.of()));
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     * @param builder function to build the paymentAllocations value
     * @return Builder
     */

    public RecurringPaymentConfigurationDraftBuilder setPaymentAllocations(
            Function<com.commercetools.api.models.cart.PaymentAllocationDraftBuilder, com.commercetools.api.models.cart.PaymentAllocationDraft> builder) {
        return paymentAllocations(builder.apply(com.commercetools.api.models.cart.PaymentAllocationDraftBuilder.of()));
    }

    /**
     *  <p>Determines how payment is collected for the Orders generated by the Recurring Order.</p>
     * @return paymentStrategy
     */

    public com.commercetools.api.models.cart.PaymentStrategy getPaymentStrategy() {
        return this.paymentStrategy;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     * @return paymentAllocations
     */

    public java.util.List<com.commercetools.api.models.cart.PaymentAllocationDraft> getPaymentAllocations() {
        return this.paymentAllocations;
    }

    /**
     * builds RecurringPaymentConfigurationDraft with checking for non-null required values
     * @return RecurringPaymentConfigurationDraft
     */
    public RecurringPaymentConfigurationDraft build() {
        Objects.requireNonNull(paymentStrategy,
            RecurringPaymentConfigurationDraft.class + ": paymentStrategy is missing");
        Objects.requireNonNull(paymentAllocations,
            RecurringPaymentConfigurationDraft.class + ": paymentAllocations is missing");
        return new RecurringPaymentConfigurationDraftImpl(paymentStrategy, paymentAllocations);
    }

    /**
     * builds RecurringPaymentConfigurationDraft without checking for non-null required values
     * @return RecurringPaymentConfigurationDraft
     */
    public RecurringPaymentConfigurationDraft buildUnchecked() {
        return new RecurringPaymentConfigurationDraftImpl(paymentStrategy, paymentAllocations);
    }

    /**
     * factory method for an instance of RecurringPaymentConfigurationDraftBuilder
     * @return builder
     */
    public static RecurringPaymentConfigurationDraftBuilder of() {
        return new RecurringPaymentConfigurationDraftBuilder();
    }

    /**
     * create builder for RecurringPaymentConfigurationDraft instance
     * @param template instance with prefilled values for the builder
     * @return builder
     */
    public static RecurringPaymentConfigurationDraftBuilder of(final RecurringPaymentConfigurationDraft template) {
        RecurringPaymentConfigurationDraftBuilder builder = new RecurringPaymentConfigurationDraftBuilder();
        builder.paymentStrategy = template.getPaymentStrategy();
        builder.paymentAllocations = template.getPaymentAllocations();
        return builder;
    }

}
