
package com.commercetools.api.models.cart;

import java.time.*;
import java.util.*;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.vrap.rmf.base.client.ModelBase;
import io.vrap.rmf.base.client.utils.Generated;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import tools.jackson.databind.annotation.*;

/**
 *  <p>Draft type that stores the data to create a <a href="https://docs.commercetools.com/apis/ctp:api:type:RecurringPaymentConfiguration" rel="nofollow">RecurringPaymentConfiguration</a>.</p>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
public class RecurringPaymentConfigurationDraftImpl implements RecurringPaymentConfigurationDraft, ModelBase {

    private com.commercetools.api.models.cart.PaymentStrategy paymentStrategy;

    private java.util.List<com.commercetools.api.models.cart.PaymentAllocationDraft> paymentAllocations;

    /**
     * create instance with all properties
     */
    @JsonCreator
    RecurringPaymentConfigurationDraftImpl(
            @JsonProperty("paymentStrategy") final com.commercetools.api.models.cart.PaymentStrategy paymentStrategy,
            @JsonProperty("paymentAllocations") final java.util.List<com.commercetools.api.models.cart.PaymentAllocationDraft> paymentAllocations) {
        this.paymentStrategy = paymentStrategy;
        this.paymentAllocations = paymentAllocations;
    }

    /**
     * create empty instance
     */
    public RecurringPaymentConfigurationDraftImpl() {
    }

    /**
     *  <p>Determines how payment is collected for the Orders generated by the Recurring Order.</p>
     */

    public com.commercetools.api.models.cart.PaymentStrategy getPaymentStrategy() {
        return this.paymentStrategy;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     */

    public java.util.List<com.commercetools.api.models.cart.PaymentAllocationDraft> getPaymentAllocations() {
        return this.paymentAllocations;
    }

    public void setPaymentStrategy(final com.commercetools.api.models.cart.PaymentStrategy paymentStrategy) {
        this.paymentStrategy = paymentStrategy;
    }

    public void setPaymentAllocations(
            final com.commercetools.api.models.cart.PaymentAllocationDraft... paymentAllocations) {
        this.paymentAllocations = new ArrayList<>(Arrays.asList(paymentAllocations));
    }

    public void setPaymentAllocations(
            final java.util.List<com.commercetools.api.models.cart.PaymentAllocationDraft> paymentAllocations) {
        this.paymentAllocations = paymentAllocations;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;

        if (o == null || getClass() != o.getClass())
            return false;

        RecurringPaymentConfigurationDraftImpl that = (RecurringPaymentConfigurationDraftImpl) o;

        return new EqualsBuilder().append(paymentStrategy, that.paymentStrategy)
                .append(paymentAllocations, that.paymentAllocations)
                .append(paymentStrategy, that.paymentStrategy)
                .append(paymentAllocations, that.paymentAllocations)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37).append(paymentStrategy).append(paymentAllocations).toHashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE).append("paymentStrategy", paymentStrategy)
                .append("paymentAllocations", paymentAllocations)
                .build();
    }

    @Override
    public RecurringPaymentConfigurationDraft copyDeep() {
        return RecurringPaymentConfigurationDraft.deepCopy(this);
    }
}
