
package com.commercetools.api.models.cart;

import java.util.*;
import java.util.function.Function;

import io.vrap.rmf.base.client.Builder;
import io.vrap.rmf.base.client.utils.Generated;

/**
 * RecurringPaymentConfigurationBuilder
 * <hr>
 * Example to create an instance using the builder pattern
 * <div class=code-example>
 * <pre><code class='java'>
 *     RecurringPaymentConfiguration recurringPaymentConfiguration = RecurringPaymentConfiguration.builder()
 *             .paymentStrategy(PaymentStrategy.CHECKOUT)
 *             .plusPaymentAllocations(paymentAllocationsBuilder -> paymentAllocationsBuilder)
 *             .build()
 * </code></pre>
 * </div>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
public class RecurringPaymentConfigurationBuilder implements Builder<RecurringPaymentConfiguration> {

    private com.commercetools.api.models.cart.PaymentStrategy paymentStrategy;

    private java.util.List<com.commercetools.api.models.cart.RecurringPaymentAllocation> paymentAllocations;

    /**
     *  <p>Determines how payment is collected for the Orders generated by the Recurring Order.</p>
     * @param paymentStrategy value to be set
     * @return Builder
     */

    public RecurringPaymentConfigurationBuilder paymentStrategy(
            final com.commercetools.api.models.cart.PaymentStrategy paymentStrategy) {
        this.paymentStrategy = paymentStrategy;
        return this;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the RecurringOrder, and the share of the Order total charged to each of them.</p>
     * @param paymentAllocations value to be set
     * @return Builder
     */

    public RecurringPaymentConfigurationBuilder paymentAllocations(
            final com.commercetools.api.models.cart.RecurringPaymentAllocation... paymentAllocations) {
        this.paymentAllocations = new ArrayList<>(Arrays.asList(paymentAllocations));
        return this;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the RecurringOrder, and the share of the Order total charged to each of them.</p>
     * @param paymentAllocations value to be set
     * @return Builder
     */

    public RecurringPaymentConfigurationBuilder paymentAllocations(
            final java.util.List<com.commercetools.api.models.cart.RecurringPaymentAllocation> paymentAllocations) {
        this.paymentAllocations = paymentAllocations;
        return this;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the RecurringOrder, and the share of the Order total charged to each of them.</p>
     * @param paymentAllocations value to be set
     * @return Builder
     */

    public RecurringPaymentConfigurationBuilder plusPaymentAllocations(
            final com.commercetools.api.models.cart.RecurringPaymentAllocation... paymentAllocations) {
        if (this.paymentAllocations == null) {
            this.paymentAllocations = new ArrayList<>();
        }
        this.paymentAllocations.addAll(Arrays.asList(paymentAllocations));
        return this;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the RecurringOrder, and the share of the Order total charged to each of them.</p>
     * @param builder function to build the paymentAllocations value
     * @return Builder
     */

    public RecurringPaymentConfigurationBuilder plusPaymentAllocations(
            Function<com.commercetools.api.models.cart.RecurringPaymentAllocationBuilder, com.commercetools.api.models.cart.RecurringPaymentAllocationBuilder> builder) {
        if (this.paymentAllocations == null) {
            this.paymentAllocations = new ArrayList<>();
        }
        this.paymentAllocations
                .add(builder.apply(com.commercetools.api.models.cart.RecurringPaymentAllocationBuilder.of()).build());
        return this;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the RecurringOrder, and the share of the Order total charged to each of them.</p>
     * @param builder function to build the paymentAllocations value
     * @return Builder
     */

    public RecurringPaymentConfigurationBuilder withPaymentAllocations(
            Function<com.commercetools.api.models.cart.RecurringPaymentAllocationBuilder, com.commercetools.api.models.cart.RecurringPaymentAllocationBuilder> builder) {
        this.paymentAllocations = new ArrayList<>();
        this.paymentAllocations
                .add(builder.apply(com.commercetools.api.models.cart.RecurringPaymentAllocationBuilder.of()).build());
        return this;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the RecurringOrder, and the share of the Order total charged to each of them.</p>
     * @param builder function to build the paymentAllocations value
     * @return Builder
     */

    public RecurringPaymentConfigurationBuilder addPaymentAllocations(
            Function<com.commercetools.api.models.cart.RecurringPaymentAllocationBuilder, com.commercetools.api.models.cart.RecurringPaymentAllocation> builder) {
        return plusPaymentAllocations(
            builder.apply(com.commercetools.api.models.cart.RecurringPaymentAllocationBuilder.of()));
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the RecurringOrder, and the share of the Order total charged to each of them.</p>
     * @param builder function to build the paymentAllocations value
     * @return Builder
     */

    public RecurringPaymentConfigurationBuilder setPaymentAllocations(
            Function<com.commercetools.api.models.cart.RecurringPaymentAllocationBuilder, com.commercetools.api.models.cart.RecurringPaymentAllocation> builder) {
        return paymentAllocations(
            builder.apply(com.commercetools.api.models.cart.RecurringPaymentAllocationBuilder.of()));
    }

    /**
     *  <p>Determines how payment is collected for the Orders generated by the Recurring Order.</p>
     * @return paymentStrategy
     */

    public com.commercetools.api.models.cart.PaymentStrategy getPaymentStrategy() {
        return this.paymentStrategy;
    }

    /**
     *  <p>Payment Methods charged for the Orders generated by the RecurringOrder, and the share of the Order total charged to each of them.</p>
     * @return paymentAllocations
     */

    public java.util.List<com.commercetools.api.models.cart.RecurringPaymentAllocation> getPaymentAllocations() {
        return this.paymentAllocations;
    }

    /**
     * builds RecurringPaymentConfiguration with checking for non-null required values
     * @return RecurringPaymentConfiguration
     */
    public RecurringPaymentConfiguration build() {
        Objects.requireNonNull(paymentStrategy, RecurringPaymentConfiguration.class + ": paymentStrategy is missing");
        Objects.requireNonNull(paymentAllocations,
            RecurringPaymentConfiguration.class + ": paymentAllocations is missing");
        return new RecurringPaymentConfigurationImpl(paymentStrategy, paymentAllocations);
    }

    /**
     * builds RecurringPaymentConfiguration without checking for non-null required values
     * @return RecurringPaymentConfiguration
     */
    public RecurringPaymentConfiguration buildUnchecked() {
        return new RecurringPaymentConfigurationImpl(paymentStrategy, paymentAllocations);
    }

    /**
     * factory method for an instance of RecurringPaymentConfigurationBuilder
     * @return builder
     */
    public static RecurringPaymentConfigurationBuilder of() {
        return new RecurringPaymentConfigurationBuilder();
    }

    /**
     * create builder for RecurringPaymentConfiguration instance
     * @param template instance with prefilled values for the builder
     * @return builder
     */
    public static RecurringPaymentConfigurationBuilder of(final RecurringPaymentConfiguration template) {
        RecurringPaymentConfigurationBuilder builder = new RecurringPaymentConfigurationBuilder();
        builder.paymentStrategy = template.getPaymentStrategy();
        builder.paymentAllocations = template.getPaymentAllocations();
        return builder;
    }

}
