
package com.commercetools.api.models.cart;

import java.time.*;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.*;

import io.vrap.rmf.base.client.utils.Generated;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import tools.jackson.databind.annotation.*;

/**
 *  <p>Draft type that stores the data to create a <a href="https://docs.commercetools.com/apis/ctp:api:type:RecurringPaymentConfiguration" rel="nofollow">RecurringPaymentConfiguration</a>.</p>
 *
 * <hr>
 * Example to create an instance using the builder pattern
 * <div class=code-example>
 * <pre><code class='java'>
 *     RecurringPaymentConfigurationDraft recurringPaymentConfigurationDraft = RecurringPaymentConfigurationDraft.builder()
 *             .paymentStrategy(PaymentStrategy.CHECKOUT)
 *             .plusPaymentAllocations(paymentAllocationsBuilder -> paymentAllocationsBuilder)
 *             .build()
 * </code></pre>
 * </div>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
@JsonDeserialize(as = RecurringPaymentConfigurationDraftImpl.class)
public interface RecurringPaymentConfigurationDraft
        extends io.vrap.rmf.base.client.Draft<RecurringPaymentConfigurationDraft> {

    /**
     *  <p>Determines how payment is collected for the Orders generated by the Recurring Order.</p>
     * @return paymentStrategy
     */
    @NotNull
    @JsonProperty("paymentStrategy")
    public PaymentStrategy getPaymentStrategy();

    /**
     *  <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     * @return paymentAllocations
     */
    @NotNull
    @Valid
    @JsonProperty("paymentAllocations")
    public List<PaymentAllocationDraft> getPaymentAllocations();

    /**
     *  <p>Determines how payment is collected for the Orders generated by the Recurring Order.</p>
     * @param paymentStrategy value to be set
     */

    public void setPaymentStrategy(final PaymentStrategy paymentStrategy);

    /**
     *  <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     * @param paymentAllocations values to be set
     */

    @JsonIgnore
    public void setPaymentAllocations(final PaymentAllocationDraft... paymentAllocations);

    /**
     *  <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     * @param paymentAllocations values to be set
     */

    public void setPaymentAllocations(final List<PaymentAllocationDraft> paymentAllocations);

    /**
     * factory method
     * @return instance of RecurringPaymentConfigurationDraft
     */
    public static RecurringPaymentConfigurationDraft of() {
        return new RecurringPaymentConfigurationDraftImpl();
    }

    /**
     * factory method to create a shallow copy RecurringPaymentConfigurationDraft
     * @param template instance to be copied
     * @return copy instance
     */
    public static RecurringPaymentConfigurationDraft of(final RecurringPaymentConfigurationDraft template) {
        RecurringPaymentConfigurationDraftImpl instance = new RecurringPaymentConfigurationDraftImpl();
        instance.setPaymentStrategy(template.getPaymentStrategy());
        instance.setPaymentAllocations(template.getPaymentAllocations());
        return instance;
    }

    public RecurringPaymentConfigurationDraft copyDeep();

    /**
     * factory method to create a deep copy of RecurringPaymentConfigurationDraft
     * @param template instance to be copied
     * @return copy instance
     */
    @Nullable
    public static RecurringPaymentConfigurationDraft deepCopy(
            @Nullable final RecurringPaymentConfigurationDraft template) {
        if (template == null) {
            return null;
        }
        RecurringPaymentConfigurationDraftImpl instance = new RecurringPaymentConfigurationDraftImpl();
        instance.setPaymentStrategy(template.getPaymentStrategy());
        instance.setPaymentAllocations(Optional.ofNullable(template.getPaymentAllocations())
                .map(t -> t.stream()
                        .map(com.commercetools.api.models.cart.PaymentAllocationDraft::deepCopy)
                        .collect(Collectors.toList()))
                .orElse(null));
        return instance;
    }

    /**
     * builder factory method for RecurringPaymentConfigurationDraft
     * @return builder
     */
    public static RecurringPaymentConfigurationDraftBuilder builder() {
        return RecurringPaymentConfigurationDraftBuilder.of();
    }

    /**
     * create builder for RecurringPaymentConfigurationDraft instance
     * @param template instance with prefilled values for the builder
     * @return builder
     */
    public static RecurringPaymentConfigurationDraftBuilder builder(final RecurringPaymentConfigurationDraft template) {
        return RecurringPaymentConfigurationDraftBuilder.of(template);
    }

    /**
     * accessor map function
     * @param <T> mapped type
     * @param helper function to map the object
     * @return mapped value
     */
    default <T> T withRecurringPaymentConfigurationDraft(Function<RecurringPaymentConfigurationDraft, T> helper) {
        return helper.apply(this);
    }

    /**
     * gives a TypeReference for usage with Jackson DataBind
     * @return TypeReference
     */
    public static tools.jackson.core.type.TypeReference<RecurringPaymentConfigurationDraft> typeReference() {
        return new tools.jackson.core.type.TypeReference<RecurringPaymentConfigurationDraft>() {
            @Override
            public String toString() {
                return "TypeReference<RecurringPaymentConfigurationDraft>";
            }
        };
    }
}
