
package com.commercetools.api.models.cart;

import java.time.*;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.*;

import io.vrap.rmf.base.client.utils.Generated;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import tools.jackson.databind.annotation.*;

/**
 *  <p>Determines how the Orders generated by a <a href="https://docs.commercetools.com/apis/ctp:api:type:RecurringOrder" rel="nofollow">RecurringOrder</a> are paid for. It is only evaluated on recurring Carts, that is Carts with the <code>RecurringOrder</code> <a href="https://docs.commercetools.com/apis/ctp:api:type:CartOrigin" rel="nofollow">CartOrigin</a>.</p>
 *
 * <hr>
 * Example to create an instance using the builder pattern
 * <div class=code-example>
 * <pre><code class='java'>
 *     RecurringPaymentConfiguration recurringPaymentConfiguration = RecurringPaymentConfiguration.builder()
 *             .paymentStrategy(PaymentStrategy.CHECKOUT)
 *             .plusPaymentAllocations(paymentAllocationsBuilder -> paymentAllocationsBuilder)
 *             .build()
 * </code></pre>
 * </div>
 */
@Generated(value = "io.vrap.rmf.codegen.rendering.CoreCodeGenerator", comments = "https://github.com/commercetools/rmf-codegen")
@JsonDeserialize(as = RecurringPaymentConfigurationImpl.class)
public interface RecurringPaymentConfiguration {

    /**
     *  <p>Determines how payment is collected for the Orders generated by the Recurring Order.</p>
     * @return paymentStrategy
     */
    @NotNull
    @JsonProperty("paymentStrategy")
    public PaymentStrategy getPaymentStrategy();

    /**
     *  <p>Payment Methods charged for the Orders generated by the RecurringOrder, and the share of the Order total charged to each of them.</p>
     * @return paymentAllocations
     */
    @NotNull
    @Valid
    @JsonProperty("paymentAllocations")
    public List<RecurringPaymentAllocation> getPaymentAllocations();

    /**
     *  <p>Determines how payment is collected for the Orders generated by the Recurring Order.</p>
     * @param paymentStrategy value to be set
     */

    public void setPaymentStrategy(final PaymentStrategy paymentStrategy);

    /**
     *  <p>Payment Methods charged for the Orders generated by the RecurringOrder, and the share of the Order total charged to each of them.</p>
     * @param paymentAllocations values to be set
     */

    @JsonIgnore
    public void setPaymentAllocations(final RecurringPaymentAllocation... paymentAllocations);

    /**
     *  <p>Payment Methods charged for the Orders generated by the RecurringOrder, and the share of the Order total charged to each of them.</p>
     * @param paymentAllocations values to be set
     */

    public void setPaymentAllocations(final List<RecurringPaymentAllocation> paymentAllocations);

    /**
     * factory method
     * @return instance of RecurringPaymentConfiguration
     */
    public static RecurringPaymentConfiguration of() {
        return new RecurringPaymentConfigurationImpl();
    }

    /**
     * factory method to create a shallow copy RecurringPaymentConfiguration
     * @param template instance to be copied
     * @return copy instance
     */
    public static RecurringPaymentConfiguration of(final RecurringPaymentConfiguration template) {
        RecurringPaymentConfigurationImpl instance = new RecurringPaymentConfigurationImpl();
        instance.setPaymentStrategy(template.getPaymentStrategy());
        instance.setPaymentAllocations(template.getPaymentAllocations());
        return instance;
    }

    public RecurringPaymentConfiguration copyDeep();

    /**
     * factory method to create a deep copy of RecurringPaymentConfiguration
     * @param template instance to be copied
     * @return copy instance
     */
    @Nullable
    public static RecurringPaymentConfiguration deepCopy(@Nullable final RecurringPaymentConfiguration template) {
        if (template == null) {
            return null;
        }
        RecurringPaymentConfigurationImpl instance = new RecurringPaymentConfigurationImpl();
        instance.setPaymentStrategy(template.getPaymentStrategy());
        instance.setPaymentAllocations(Optional.ofNullable(template.getPaymentAllocations())
                .map(t -> t.stream()
                        .map(com.commercetools.api.models.cart.RecurringPaymentAllocation::deepCopy)
                        .collect(Collectors.toList()))
                .orElse(null));
        return instance;
    }

    /**
     * builder factory method for RecurringPaymentConfiguration
     * @return builder
     */
    public static RecurringPaymentConfigurationBuilder builder() {
        return RecurringPaymentConfigurationBuilder.of();
    }

    /**
     * create builder for RecurringPaymentConfiguration instance
     * @param template instance with prefilled values for the builder
     * @return builder
     */
    public static RecurringPaymentConfigurationBuilder builder(final RecurringPaymentConfiguration template) {
        return RecurringPaymentConfigurationBuilder.of(template);
    }

    /**
     * accessor map function
     * @param <T> mapped type
     * @param helper function to map the object
     * @return mapped value
     */
    default <T> T withRecurringPaymentConfiguration(Function<RecurringPaymentConfiguration, T> helper) {
        return helper.apply(this);
    }

    /**
     * gives a TypeReference for usage with Jackson DataBind
     * @return TypeReference
     */
    public static tools.jackson.core.type.TypeReference<RecurringPaymentConfiguration> typeReference() {
        return new tools.jackson.core.type.TypeReference<RecurringPaymentConfiguration>() {
            @Override
            public String toString() {
                return "TypeReference<RecurringPaymentConfiguration>";
            }
        };
    }
}
